/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.AbsenzStatus;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AbsenzStatusRecord extends UpdatableRecordImpl<AbsenzStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.absenz_status.fk_login</code>.
     */
    public void setFkLogin(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.absenz_status.fk_login</code>.
     */
    public Long getFkLogin() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.absenz_status.fk_event</code>.
     */
    public void setFkEvent(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.absenz_status.fk_event</code>.
     */
    public Long getFkEvent() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.absenz_status.remark</code>.
     */
    public void setRemark(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.absenz_status.remark</code>.
     */
    public String getRemark() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.absenz_status.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.absenz_status.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AbsenzStatusRecord
     */
    public AbsenzStatusRecord() {
        super(AbsenzStatus.ABSENZ_STATUS);
    }

    /**
     * Create a detached, initialised AbsenzStatusRecord
     */
    public AbsenzStatusRecord(Long fkLogin, Long fkEvent, String remark, String status) {
        super(AbsenzStatus.ABSENZ_STATUS);

        setFkLogin(fkLogin);
        setFkEvent(fkEvent);
        setRemark(remark);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AbsenzStatusRecord
     */
    public AbsenzStatusRecord(ch.mvurdorf.platform.jooq.tables.pojos.AbsenzStatus value) {
        super(AbsenzStatus.ABSENZ_STATUS);

        if (value != null) {
            setFkLogin(value.getFkLogin());
            setFkEvent(value.getFkEvent());
            setRemark(value.getRemark());
            setStatus(value.getStatus());
            resetChangedOnNotNull();
        }
    }
}
