/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.Document;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocumentRecord extends UpdatableRecordImpl<DocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.document.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.document.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.document.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.document.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.document.file_type</code>.
     */
    public void setFileType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.document.file_type</code>.
     */
    public String getFileType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.document.upload_date</code>.
     */
    public void setUploadDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.document.upload_date</code>.
     */
    public LocalDateTime getUploadDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.document.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.document.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocumentRecord
     */
    public DocumentRecord() {
        super(Document.DOCUMENT);
    }

    /**
     * Create a detached, initialised DocumentRecord
     */
    public DocumentRecord(Long id, String name, String fileType, LocalDateTime uploadDate, String description) {
        super(Document.DOCUMENT);

        setId(id);
        setName(name);
        setFileType(fileType);
        setUploadDate(uploadDate);
        setDescription(description);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DocumentRecord
     */
    public DocumentRecord(ch.mvurdorf.platform.jooq.tables.pojos.Document value) {
        super(Document.DOCUMENT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setFileType(value.getFileType());
            setUploadDate(value.getUploadDate());
            setDescription(value.getDescription());
            resetChangedOnNotNull();
        }
    }
}
