/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.KonzertEntry;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KonzertEntryRecord extends UpdatableRecordImpl<KonzertEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.konzert_entry.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.konzert_entry.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.konzert_entry.fk_konzert</code>.
     */
    public void setFkKonzert(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.konzert_entry.fk_konzert</code>.
     */
    public Long getFkKonzert() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.konzert_entry.index</code>.
     */
    public void setIndex(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.konzert_entry.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.konzert_entry.fk_komposition</code>.
     */
    public void setFkKomposition(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.konzert_entry.fk_komposition</code>.
     */
    public Long getFkKomposition() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.konzert_entry.placeholder</code>.
     */
    public void setPlaceholder(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.konzert_entry.placeholder</code>.
     */
    public String getPlaceholder() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.konzert_entry.zugabe</code>.
     */
    public void setZugabe(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.konzert_entry.zugabe</code>.
     */
    public Boolean getZugabe() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KonzertEntryRecord
     */
    public KonzertEntryRecord() {
        super(KonzertEntry.KONZERT_ENTRY);
    }

    /**
     * Create a detached, initialised KonzertEntryRecord
     */
    public KonzertEntryRecord(Long id, Long fkKonzert, Integer index, Long fkKomposition, String placeholder, Boolean zugabe) {
        super(KonzertEntry.KONZERT_ENTRY);

        setId(id);
        setFkKonzert(fkKonzert);
        setIndex(index);
        setFkKomposition(fkKomposition);
        setPlaceholder(placeholder);
        setZugabe(zugabe);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised KonzertEntryRecord
     */
    public KonzertEntryRecord(ch.mvurdorf.platform.jooq.tables.pojos.KonzertEntry value) {
        super(KonzertEntry.KONZERT_ENTRY);

        if (value != null) {
            setId(value.getId());
            setFkKonzert(value.getFkKonzert());
            setIndex(value.getIndex());
            setFkKomposition(value.getFkKomposition());
            setPlaceholder(value.getPlaceholder());
            setZugabe(value.getZugabe());
            resetChangedOnNotNull();
        }
    }
}
