/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.Konzert;

import java.time.LocalDate;
import java.time.LocalTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KonzertRecord extends UpdatableRecordImpl<KonzertRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.konzert.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.konzert.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.konzert.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.konzert.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.konzert.datum</code>.
     */
    public void setDatum(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.konzert.datum</code>.
     */
    public LocalDate getDatum() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.konzert.zeit</code>.
     */
    public void setZeit(LocalTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.konzert.zeit</code>.
     */
    public LocalTime getZeit() {
        return (LocalTime) get(3);
    }

    /**
     * Setter for <code>public.konzert.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.konzert.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.konzert.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.konzert.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.konzert.tenu</code>.
     */
    public void setTenu(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.konzert.tenu</code>.
     */
    public String getTenu() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KonzertRecord
     */
    public KonzertRecord() {
        super(Konzert.KONZERT);
    }

    /**
     * Create a detached, initialised KonzertRecord
     */
    public KonzertRecord(Long id, String name, LocalDate datum, LocalTime zeit, String location, String description, String tenu) {
        super(Konzert.KONZERT);

        setId(id);
        setName(name);
        setDatum(datum);
        setZeit(zeit);
        setLocation(location);
        setDescription(description);
        setTenu(tenu);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised KonzertRecord
     */
    public KonzertRecord(ch.mvurdorf.platform.jooq.tables.pojos.Konzert value) {
        super(Konzert.KONZERT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDatum(value.getDatum());
            setZeit(value.getZeit());
            setLocation(value.getLocation());
            setDescription(value.getDescription());
            setTenu(value.getTenu());
            resetChangedOnNotNull();
        }
    }
}
