/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.Noten;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotenRecord extends UpdatableRecordImpl<NotenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.noten.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.noten.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.noten.fk_komposition</code>.
     */
    public void setFkKomposition(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.noten.fk_komposition</code>.
     */
    public Long getFkKomposition() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.noten.instrument</code>.
     */
    public void setInstrument(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.noten.instrument</code>.
     */
    public String getInstrument() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.noten.stimme</code>.
     */
    public void setStimme(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.noten.stimme</code>.
     */
    public String getStimme() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.noten.stimmlage</code>.
     */
    public void setStimmlage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.noten.stimmlage</code>.
     */
    public String getStimmlage() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotenRecord
     */
    public NotenRecord() {
        super(Noten.NOTEN);
    }

    /**
     * Create a detached, initialised NotenRecord
     */
    public NotenRecord(Long id, Long fkKomposition, String instrument, String stimme, String stimmlage) {
        super(Noten.NOTEN);

        setId(id);
        setFkKomposition(fkKomposition);
        setInstrument(instrument);
        setStimme(stimme);
        setStimmlage(stimmlage);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NotenRecord
     */
    public NotenRecord(ch.mvurdorf.platform.jooq.tables.pojos.Noten value) {
        super(Noten.NOTEN);

        if (value != null) {
            setId(value.getId());
            setFkKomposition(value.getFkKomposition());
            setInstrument(value.getInstrument());
            setStimme(value.getStimme());
            setStimmlage(value.getStimmlage());
            resetChangedOnNotNull();
        }
    }
}
