/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.NotenPdfAssignment;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotenPdfAssignmentRecord extends UpdatableRecordImpl<NotenPdfAssignmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.noten_pdf_assignment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.noten_pdf_assignment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.noten_pdf_assignment.fk_noten_pdf</code>.
     */
    public void setFkNotenPdf(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.noten_pdf_assignment.fk_noten_pdf</code>.
     */
    public Long getFkNotenPdf() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.noten_pdf_assignment.instrument</code>.
     */
    public void setInstrument(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.noten_pdf_assignment.instrument</code>.
     */
    public String getInstrument() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.noten_pdf_assignment.stimme</code>.
     */
    public void setStimme(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.noten_pdf_assignment.stimme</code>.
     */
    public String getStimme() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotenPdfAssignmentRecord
     */
    public NotenPdfAssignmentRecord() {
        super(NotenPdfAssignment.NOTEN_PDF_ASSIGNMENT);
    }

    /**
     * Create a detached, initialised NotenPdfAssignmentRecord
     */
    public NotenPdfAssignmentRecord(Long id, Long fkNotenPdf, String instrument, String stimme) {
        super(NotenPdfAssignment.NOTEN_PDF_ASSIGNMENT);

        setId(id);
        setFkNotenPdf(fkNotenPdf);
        setInstrument(instrument);
        setStimme(stimme);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NotenPdfAssignmentRecord
     */
    public NotenPdfAssignmentRecord(ch.mvurdorf.platform.jooq.tables.pojos.NotenPdfAssignment value) {
        super(NotenPdfAssignment.NOTEN_PDF_ASSIGNMENT);

        if (value != null) {
            setId(value.getId());
            setFkNotenPdf(value.getFkNotenPdf());
            setInstrument(value.getInstrument());
            setStimme(value.getStimme());
            resetChangedOnNotNull();
        }
    }
}
