/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.Repertoire;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RepertoireRecord extends UpdatableRecordImpl<RepertoireRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.repertoire.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.repertoire.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.repertoire.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.repertoire.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.repertoire.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.repertoire.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.repertoire.details</code>.
     */
    public void setDetails(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.repertoire.details</code>.
     */
    public String getDetails() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RepertoireRecord
     */
    public RepertoireRecord() {
        super(Repertoire.REPERTOIRE);
    }

    /**
     * Create a detached, initialised RepertoireRecord
     */
    public RepertoireRecord(Long id, String type, LocalDateTime createdAt, String details) {
        super(Repertoire.REPERTOIRE);

        setId(id);
        setType(type);
        setCreatedAt(createdAt);
        setDetails(details);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RepertoireRecord
     */
    public RepertoireRecord(ch.mvurdorf.platform.jooq.tables.pojos.Repertoire value) {
        super(Repertoire.REPERTOIRE);

        if (value != null) {
            setId(value.getId());
            setType(value.getType());
            setCreatedAt(value.getCreatedAt());
            setDetails(value.getDetails());
            resetChangedOnNotNull();
        }
    }
}
