/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.ShareableLink;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShareableLinkRecord extends UpdatableRecordImpl<ShareableLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shareable_link.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shareable_link.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.shareable_link.uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shareable_link.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shareable_link.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shareable_link.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.shareable_link.valid_until</code>.
     */
    public void setValidUntil(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shareable_link.valid_until</code>.
     */
    public LocalDate getValidUntil() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShareableLinkRecord
     */
    public ShareableLinkRecord() {
        super(ShareableLink.SHAREABLE_LINK);
    }

    /**
     * Create a detached, initialised ShareableLinkRecord
     */
    public ShareableLinkRecord(Long id, String uuid, String description, LocalDate validUntil) {
        super(ShareableLink.SHAREABLE_LINK);

        setId(id);
        setUuid(uuid);
        setDescription(description);
        setValidUntil(validUntil);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ShareableLinkRecord
     */
    public ShareableLinkRecord(ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink value) {
        super(ShareableLink.SHAREABLE_LINK);

        if (value != null) {
            setId(value.getId());
            setUuid(value.getUuid());
            setDescription(value.getDescription());
            setValidUntil(value.getValidUntil());
            resetChangedOnNotNull();
        }
    }
}
