/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.ShareableLinkKomposition;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShareableLinkKompositionRecord extends UpdatableRecordImpl<ShareableLinkKompositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shareable_link_komposition.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shareable_link_komposition.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.shareable_link_komposition.shareable_link_id</code>.
     */
    public void setShareableLinkId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.shareable_link_komposition.shareable_link_id</code>.
     */
    public Long getShareableLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.shareable_link_komposition.komposition_id</code>.
     */
    public void setKompositionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shareable_link_komposition.komposition_id</code>.
     */
    public Long getKompositionId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShareableLinkKompositionRecord
     */
    public ShareableLinkKompositionRecord() {
        super(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION);
    }

    /**
     * Create a detached, initialised ShareableLinkKompositionRecord
     */
    public ShareableLinkKompositionRecord(Long id, Long shareableLinkId, Long kompositionId) {
        super(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION);

        setId(id);
        setShareableLinkId(shareableLinkId);
        setKompositionId(kompositionId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ShareableLinkKompositionRecord
     */
    public ShareableLinkKompositionRecord(ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition value) {
        super(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION);

        if (value != null) {
            setId(value.getId());
            setShareableLinkId(value.getShareableLinkId());
            setKompositionId(value.getKompositionId());
            resetChangedOnNotNull();
        }
    }
}
