/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.ShareableLinkInstrument;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShareableLinkInstrumentRecord extends UpdatableRecordImpl<ShareableLinkInstrumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shareable_link_instrument.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shareable_link_instrument.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.shareable_link_instrument.shareable_link_id</code>.
     */
    public void setShareableLinkId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.shareable_link_instrument.shareable_link_id</code>.
     */
    public Long getShareableLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.shareable_link_instrument.instrument</code>.
     */
    public void setInstrument(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shareable_link_instrument.instrument</code>.
     */
    public String getInstrument() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShareableLinkInstrumentRecord
     */
    public ShareableLinkInstrumentRecord() {
        super(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT);
    }

    /**
     * Create a detached, initialised ShareableLinkInstrumentRecord
     */
    public ShareableLinkInstrumentRecord(Long id, Long shareableLinkId, String instrument) {
        super(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT);

        setId(id);
        setShareableLinkId(shareableLinkId);
        setInstrument(instrument);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ShareableLinkInstrumentRecord
     */
    public ShareableLinkInstrumentRecord(ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument value) {
        super(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT);

        if (value != null) {
            setId(value.getId());
            setShareableLinkId(value.getShareableLinkId());
            setInstrument(value.getInstrument());
            resetChangedOnNotNull();
        }
    }
}
