/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.SupporterPayment;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupporterPaymentRecord extends UpdatableRecordImpl<SupporterPaymentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supporter_payment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supporter_payment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.supporter_payment.fk_supporter</code>.
     */
    public void setFkSupporter(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supporter_payment.fk_supporter</code>.
     */
    public Long getFkSupporter() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.supporter_payment.datum</code>.
     */
    public void setDatum(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supporter_payment.datum</code>.
     */
    public LocalDate getDatum() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.supporter_payment.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.supporter_payment.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.supporter_payment.bemerkung</code>.
     */
    public void setBemerkung(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.supporter_payment.bemerkung</code>.
     */
    public String getBemerkung() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.supporter_payment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.supporter_payment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.supporter_payment.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.supporter_payment.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupporterPaymentRecord
     */
    public SupporterPaymentRecord() {
        super(SupporterPayment.SUPPORTER_PAYMENT);
    }

    /**
     * Create a detached, initialised SupporterPaymentRecord
     */
    public SupporterPaymentRecord(Long id, Long fkSupporter, LocalDate datum, BigDecimal amount, String bemerkung, LocalDateTime createdAt, String createdBy) {
        super(SupporterPayment.SUPPORTER_PAYMENT);

        setId(id);
        setFkSupporter(fkSupporter);
        setDatum(datum);
        setAmount(amount);
        setBemerkung(bemerkung);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SupporterPaymentRecord
     */
    public SupporterPaymentRecord(ch.mvurdorf.platform.jooq.tables.pojos.SupporterPayment value) {
        super(SupporterPayment.SUPPORTER_PAYMENT);

        if (value != null) {
            setId(value.getId());
            setFkSupporter(value.getFkSupporter());
            setDatum(value.getDatum());
            setAmount(value.getAmount());
            setBemerkung(value.getBemerkung());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            resetChangedOnNotNull();
        }
    }
}
