/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.UserCredentials;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserCredentialsRecord extends UpdatableRecordImpl<UserCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_credentials.credential_id</code>.
     */
    public void setCredentialId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_credentials.credential_id</code>.
     */
    public String getCredentialId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_credentials.user_entity_user_id</code>.
     */
    public void setUserEntityUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_credentials.user_entity_user_id</code>.
     */
    public String getUserEntityUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_credentials.public_key</code>.
     */
    public void setPublicKey(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_credentials.public_key</code>.
     */
    public byte[] getPublicKey() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.user_credentials.signature_count</code>.
     */
    public void setSignatureCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_credentials.signature_count</code>.
     */
    public Long getSignatureCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.user_credentials.uv_initialized</code>.
     */
    public void setUvInitialized(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_credentials.uv_initialized</code>.
     */
    public Boolean getUvInitialized() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.user_credentials.backup_eligible</code>.
     */
    public void setBackupEligible(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_credentials.backup_eligible</code>.
     */
    public Boolean getBackupEligible() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.user_credentials.authenticator_transports</code>.
     */
    public void setAuthenticatorTransports(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_credentials.authenticator_transports</code>.
     */
    public String getAuthenticatorTransports() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.user_credentials.public_key_credential_type</code>.
     */
    public void setPublicKeyCredentialType(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.user_credentials.public_key_credential_type</code>.
     */
    public String getPublicKeyCredentialType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.user_credentials.backup_state</code>.
     */
    public void setBackupState(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_credentials.backup_state</code>.
     */
    public Boolean getBackupState() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.user_credentials.attestation_object</code>.
     */
    public void setAttestationObject(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user_credentials.attestation_object</code>.
     */
    public byte[] getAttestationObject() {
        return (byte[]) get(9);
    }

    /**
     * Setter for
     * <code>public.user_credentials.attestation_client_data_json</code>.
     */
    public void setAttestationClientDataJson(byte[] value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.user_credentials.attestation_client_data_json</code>.
     */
    public byte[] getAttestationClientDataJson() {
        return (byte[]) get(10);
    }

    /**
     * Setter for <code>public.user_credentials.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.user_credentials.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.user_credentials.last_used</code>.
     */
    public void setLastUsed(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.user_credentials.last_used</code>.
     */
    public LocalDateTime getLastUsed() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.user_credentials.label</code>.
     */
    public void setLabel(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.user_credentials.label</code>.
     */
    public String getLabel() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserCredentialsRecord
     */
    public UserCredentialsRecord() {
        super(UserCredentials.USER_CREDENTIALS);
    }

    /**
     * Create a detached, initialised UserCredentialsRecord
     */
    public UserCredentialsRecord(String credentialId, String userEntityUserId, byte[] publicKey, Long signatureCount, Boolean uvInitialized, Boolean backupEligible, String authenticatorTransports, String publicKeyCredentialType, Boolean backupState, byte[] attestationObject, byte[] attestationClientDataJson, LocalDateTime created, LocalDateTime lastUsed, String label) {
        super(UserCredentials.USER_CREDENTIALS);

        setCredentialId(credentialId);
        setUserEntityUserId(userEntityUserId);
        setPublicKey(publicKey);
        setSignatureCount(signatureCount);
        setUvInitialized(uvInitialized);
        setBackupEligible(backupEligible);
        setAuthenticatorTransports(authenticatorTransports);
        setPublicKeyCredentialType(publicKeyCredentialType);
        setBackupState(backupState);
        setAttestationObject(attestationObject);
        setAttestationClientDataJson(attestationClientDataJson);
        setCreated(created);
        setLastUsed(lastUsed);
        setLabel(label);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserCredentialsRecord
     */
    public UserCredentialsRecord(ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials value) {
        super(UserCredentials.USER_CREDENTIALS);

        if (value != null) {
            setCredentialId(value.getCredentialId());
            setUserEntityUserId(value.getUserEntityUserId());
            setPublicKey(value.getPublicKey());
            setSignatureCount(value.getSignatureCount());
            setUvInitialized(value.getUvInitialized());
            setBackupEligible(value.getBackupEligible());
            setAuthenticatorTransports(value.getAuthenticatorTransports());
            setPublicKeyCredentialType(value.getPublicKeyCredentialType());
            setBackupState(value.getBackupState());
            setAttestationObject(value.getAttestationObject());
            setAttestationClientDataJson(value.getAttestationClientDataJson());
            setCreated(value.getCreated());
            setLastUsed(value.getLastUsed());
            setLabel(value.getLabel());
            resetTouchedOnNotNull();
        }
    }
}
