/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.UserEntities;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserEntitiesRecord extends UpdatableRecordImpl<UserEntitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_entities.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_entities.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_entities.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_entities.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_entities.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_entities.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserEntitiesRecord
     */
    public UserEntitiesRecord() {
        super(UserEntities.USER_ENTITIES);
    }

    /**
     * Create a detached, initialised UserEntitiesRecord
     */
    public UserEntitiesRecord(String id, String name, String displayName) {
        super(UserEntities.USER_ENTITIES);

        setId(id);
        setName(name);
        setDisplayName(displayName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserEntitiesRecord
     */
    public UserEntitiesRecord(ch.mvurdorf.platform.jooq.tables.pojos.UserEntities value) {
        super(UserEntities.USER_ENTITIES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDisplayName(value.getDisplayName());
            resetTouchedOnNotNull();
        }
    }
}
