/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.records;


import ch.mvurdorf.platform.jooq.tables.Voucher;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoucherRecord extends UpdatableRecordImpl<VoucherRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.voucher.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.voucher.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.voucher.code_prefix</code>.
     */
    public void setCodePrefix(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.voucher.code_prefix</code>.
     */
    public String getCodePrefix() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.voucher.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.voucher.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.voucher.valid_until</code>.
     */
    public void setValidUntil(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.voucher.valid_until</code>.
     */
    public LocalDate getValidUntil() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.voucher.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.voucher.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoucherRecord
     */
    public VoucherRecord() {
        super(Voucher.VOUCHER);
    }

    /**
     * Create a detached, initialised VoucherRecord
     */
    public VoucherRecord(Long id, String codePrefix, String description, LocalDate validUntil, String type) {
        super(Voucher.VOUCHER);

        setId(id);
        setCodePrefix(codePrefix);
        setDescription(description);
        setValidUntil(validUntil);
        setType(type);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VoucherRecord
     */
    public VoucherRecord(ch.mvurdorf.platform.jooq.tables.pojos.Voucher value) {
        super(Voucher.VOUCHER);

        if (value != null) {
            setId(value.getId());
            setCodePrefix(value.getCodePrefix());
            setDescription(value.getDescription());
            setValidUntil(value.getValidUntil());
            setType(value.getType());
            resetChangedOnNotNull();
        }
    }
}
