/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AbsenzStatus implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long fkLogin;
    private Long fkEvent;
    private String remark;
    private String status;

    public AbsenzStatus() {}

    public AbsenzStatus(AbsenzStatus value) {
        this.fkLogin = value.fkLogin;
        this.fkEvent = value.fkEvent;
        this.remark = value.remark;
        this.status = value.status;
    }

    public AbsenzStatus(
        Long fkLogin,
        Long fkEvent,
        String remark,
        String status
    ) {
        this.fkLogin = fkLogin;
        this.fkEvent = fkEvent;
        this.remark = remark;
        this.status = status;
    }

    /**
     * Getter for <code>public.absenz_status.fk_login</code>.
     */
    public Long getFkLogin() {
        return this.fkLogin;
    }

    /**
     * Setter for <code>public.absenz_status.fk_login</code>.
     */
    public void setFkLogin(Long fkLogin) {
        this.fkLogin = fkLogin;
    }

    /**
     * Getter for <code>public.absenz_status.fk_event</code>.
     */
    public Long getFkEvent() {
        return this.fkEvent;
    }

    /**
     * Setter for <code>public.absenz_status.fk_event</code>.
     */
    public void setFkEvent(Long fkEvent) {
        this.fkEvent = fkEvent;
    }

    /**
     * Getter for <code>public.absenz_status.remark</code>.
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>public.absenz_status.remark</code>.
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Getter for <code>public.absenz_status.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.absenz_status.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AbsenzStatus other = (AbsenzStatus) obj;
        if (this.fkLogin == null) {
            if (other.fkLogin != null)
                return false;
        }
        else if (!this.fkLogin.equals(other.fkLogin))
            return false;
        if (this.fkEvent == null) {
            if (other.fkEvent != null)
                return false;
        }
        else if (!this.fkEvent.equals(other.fkEvent))
            return false;
        if (this.remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!this.remark.equals(other.remark))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.fkLogin == null) ? 0 : this.fkLogin.hashCode());
        result = prime * result + ((this.fkEvent == null) ? 0 : this.fkEvent.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AbsenzStatus (");

        sb.append(fkLogin);
        sb.append(", ").append(fkEvent);
        sb.append(", ").append(remark);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
