/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Document implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String fileType;
    private LocalDateTime uploadDate;
    private String description;

    public Document() {}

    public Document(Document value) {
        this.id = value.id;
        this.name = value.name;
        this.fileType = value.fileType;
        this.uploadDate = value.uploadDate;
        this.description = value.description;
    }

    public Document(
        Long id,
        String name,
        String fileType,
        LocalDateTime uploadDate,
        String description
    ) {
        this.id = id;
        this.name = name;
        this.fileType = fileType;
        this.uploadDate = uploadDate;
        this.description = description;
    }

    /**
     * Getter for <code>public.document.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.document.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.document.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.document.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.document.file_type</code>.
     */
    public String getFileType() {
        return this.fileType;
    }

    /**
     * Setter for <code>public.document.file_type</code>.
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * Getter for <code>public.document.upload_date</code>.
     */
    public LocalDateTime getUploadDate() {
        return this.uploadDate;
    }

    /**
     * Setter for <code>public.document.upload_date</code>.
     */
    public void setUploadDate(LocalDateTime uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * Getter for <code>public.document.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.document.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Document other = (Document) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.fileType == null) {
            if (other.fileType != null)
                return false;
        }
        else if (!this.fileType.equals(other.fileType))
            return false;
        if (this.uploadDate == null) {
            if (other.uploadDate != null)
                return false;
        }
        else if (!this.uploadDate.equals(other.uploadDate))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.fileType == null) ? 0 : this.fileType.hashCode());
        result = prime * result + ((this.uploadDate == null) ? 0 : this.uploadDate.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(fileType);
        sb.append(", ").append(uploadDate);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
