/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Komposition implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String titel;
    private String komponist;
    private String arrangeur;
    private Integer durationinseconds;

    public Komposition() {}

    public Komposition(Komposition value) {
        this.id = value.id;
        this.titel = value.titel;
        this.komponist = value.komponist;
        this.arrangeur = value.arrangeur;
        this.durationinseconds = value.durationinseconds;
    }

    public Komposition(
        Long id,
        String titel,
        String komponist,
        String arrangeur,
        Integer durationinseconds
    ) {
        this.id = id;
        this.titel = titel;
        this.komponist = komponist;
        this.arrangeur = arrangeur;
        this.durationinseconds = durationinseconds;
    }

    /**
     * Getter for <code>public.komposition.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.komposition.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.komposition.titel</code>.
     */
    public String getTitel() {
        return this.titel;
    }

    /**
     * Setter for <code>public.komposition.titel</code>.
     */
    public void setTitel(String titel) {
        this.titel = titel;
    }

    /**
     * Getter for <code>public.komposition.komponist</code>.
     */
    public String getKomponist() {
        return this.komponist;
    }

    /**
     * Setter for <code>public.komposition.komponist</code>.
     */
    public void setKomponist(String komponist) {
        this.komponist = komponist;
    }

    /**
     * Getter for <code>public.komposition.arrangeur</code>.
     */
    public String getArrangeur() {
        return this.arrangeur;
    }

    /**
     * Setter for <code>public.komposition.arrangeur</code>.
     */
    public void setArrangeur(String arrangeur) {
        this.arrangeur = arrangeur;
    }

    /**
     * Getter for <code>public.komposition.durationinseconds</code>.
     */
    public Integer getDurationinseconds() {
        return this.durationinseconds;
    }

    /**
     * Setter for <code>public.komposition.durationinseconds</code>.
     */
    public void setDurationinseconds(Integer durationinseconds) {
        this.durationinseconds = durationinseconds;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Komposition other = (Komposition) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.titel == null) {
            if (other.titel != null)
                return false;
        }
        else if (!this.titel.equals(other.titel))
            return false;
        if (this.komponist == null) {
            if (other.komponist != null)
                return false;
        }
        else if (!this.komponist.equals(other.komponist))
            return false;
        if (this.arrangeur == null) {
            if (other.arrangeur != null)
                return false;
        }
        else if (!this.arrangeur.equals(other.arrangeur))
            return false;
        if (this.durationinseconds == null) {
            if (other.durationinseconds != null)
                return false;
        }
        else if (!this.durationinseconds.equals(other.durationinseconds))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.titel == null) ? 0 : this.titel.hashCode());
        result = prime * result + ((this.komponist == null) ? 0 : this.komponist.hashCode());
        result = prime * result + ((this.arrangeur == null) ? 0 : this.arrangeur.hashCode());
        result = prime * result + ((this.durationinseconds == null) ? 0 : this.durationinseconds.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Komposition (");

        sb.append(id);
        sb.append(", ").append(titel);
        sb.append(", ").append(komponist);
        sb.append(", ").append(arrangeur);
        sb.append(", ").append(durationinseconds);

        sb.append(")");
        return sb.toString();
    }
}
