/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KonzertEntry implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long fkKonzert;
    private Integer index;
    private Long fkKomposition;
    private String placeholder;
    private Boolean zugabe;

    public KonzertEntry() {}

    public KonzertEntry(KonzertEntry value) {
        this.id = value.id;
        this.fkKonzert = value.fkKonzert;
        this.index = value.index;
        this.fkKomposition = value.fkKomposition;
        this.placeholder = value.placeholder;
        this.zugabe = value.zugabe;
    }

    public KonzertEntry(
        Long id,
        Long fkKonzert,
        Integer index,
        Long fkKomposition,
        String placeholder,
        Boolean zugabe
    ) {
        this.id = id;
        this.fkKonzert = fkKonzert;
        this.index = index;
        this.fkKomposition = fkKomposition;
        this.placeholder = placeholder;
        this.zugabe = zugabe;
    }

    /**
     * Getter for <code>public.konzert_entry.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.konzert_entry.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.konzert_entry.fk_konzert</code>.
     */
    public Long getFkKonzert() {
        return this.fkKonzert;
    }

    /**
     * Setter for <code>public.konzert_entry.fk_konzert</code>.
     */
    public void setFkKonzert(Long fkKonzert) {
        this.fkKonzert = fkKonzert;
    }

    /**
     * Getter for <code>public.konzert_entry.index</code>.
     */
    public Integer getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>public.konzert_entry.index</code>.
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * Getter for <code>public.konzert_entry.fk_komposition</code>.
     */
    public Long getFkKomposition() {
        return this.fkKomposition;
    }

    /**
     * Setter for <code>public.konzert_entry.fk_komposition</code>.
     */
    public void setFkKomposition(Long fkKomposition) {
        this.fkKomposition = fkKomposition;
    }

    /**
     * Getter for <code>public.konzert_entry.placeholder</code>.
     */
    public String getPlaceholder() {
        return this.placeholder;
    }

    /**
     * Setter for <code>public.konzert_entry.placeholder</code>.
     */
    public void setPlaceholder(String placeholder) {
        this.placeholder = placeholder;
    }

    /**
     * Getter for <code>public.konzert_entry.zugabe</code>.
     */
    public Boolean getZugabe() {
        return this.zugabe;
    }

    /**
     * Setter for <code>public.konzert_entry.zugabe</code>.
     */
    public void setZugabe(Boolean zugabe) {
        this.zugabe = zugabe;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final KonzertEntry other = (KonzertEntry) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fkKonzert == null) {
            if (other.fkKonzert != null)
                return false;
        }
        else if (!this.fkKonzert.equals(other.fkKonzert))
            return false;
        if (this.index == null) {
            if (other.index != null)
                return false;
        }
        else if (!this.index.equals(other.index))
            return false;
        if (this.fkKomposition == null) {
            if (other.fkKomposition != null)
                return false;
        }
        else if (!this.fkKomposition.equals(other.fkKomposition))
            return false;
        if (this.placeholder == null) {
            if (other.placeholder != null)
                return false;
        }
        else if (!this.placeholder.equals(other.placeholder))
            return false;
        if (this.zugabe == null) {
            if (other.zugabe != null)
                return false;
        }
        else if (!this.zugabe.equals(other.zugabe))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fkKonzert == null) ? 0 : this.fkKonzert.hashCode());
        result = prime * result + ((this.index == null) ? 0 : this.index.hashCode());
        result = prime * result + ((this.fkKomposition == null) ? 0 : this.fkKomposition.hashCode());
        result = prime * result + ((this.placeholder == null) ? 0 : this.placeholder.hashCode());
        result = prime * result + ((this.zugabe == null) ? 0 : this.zugabe.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("KonzertEntry (");

        sb.append(id);
        sb.append(", ").append(fkKonzert);
        sb.append(", ").append(index);
        sb.append(", ").append(fkKomposition);
        sb.append(", ").append(placeholder);
        sb.append(", ").append(zugabe);

        sb.append(")");
        return sb.toString();
    }
}
