/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Konzert implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private LocalDate datum;
    private LocalTime zeit;
    private String location;
    private String description;

    public Konzert() {}

    public Konzert(Konzert value) {
        this.id = value.id;
        this.name = value.name;
        this.datum = value.datum;
        this.zeit = value.zeit;
        this.location = value.location;
        this.description = value.description;
    }

    public Konzert(
        Long id,
        String name,
        LocalDate datum,
        LocalTime zeit,
        String location,
        String description
    ) {
        this.id = id;
        this.name = name;
        this.datum = datum;
        this.zeit = zeit;
        this.location = location;
        this.description = description;
    }

    /**
     * Getter for <code>public.konzert.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.konzert.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.konzert.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.konzert.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.konzert.datum</code>.
     */
    public LocalDate getDatum() {
        return this.datum;
    }

    /**
     * Setter for <code>public.konzert.datum</code>.
     */
    public void setDatum(LocalDate datum) {
        this.datum = datum;
    }

    /**
     * Getter for <code>public.konzert.zeit</code>.
     */
    public LocalTime getZeit() {
        return this.zeit;
    }

    /**
     * Setter for <code>public.konzert.zeit</code>.
     */
    public void setZeit(LocalTime zeit) {
        this.zeit = zeit;
    }

    /**
     * Getter for <code>public.konzert.location</code>.
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Setter for <code>public.konzert.location</code>.
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Getter for <code>public.konzert.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.konzert.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Konzert other = (Konzert) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.datum == null) {
            if (other.datum != null)
                return false;
        }
        else if (!this.datum.equals(other.datum))
            return false;
        if (this.zeit == null) {
            if (other.zeit != null)
                return false;
        }
        else if (!this.zeit.equals(other.zeit))
            return false;
        if (this.location == null) {
            if (other.location != null)
                return false;
        }
        else if (!this.location.equals(other.location))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.datum == null) ? 0 : this.datum.hashCode());
        result = prime * result + ((this.zeit == null) ? 0 : this.zeit.hashCode());
        result = prime * result + ((this.location == null) ? 0 : this.location.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Konzert (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(datum);
        sb.append(", ").append(zeit);
        sb.append(", ").append(location);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
