/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotenShareLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long fkKonzert;
    private String instrument;
    private UUID token;
    private LocalDateTime expiresAt;
    private Boolean active;
    private LocalDateTime createdAt;

    public NotenShareLink() {}

    public NotenShareLink(NotenShareLink value) {
        this.id = value.id;
        this.fkKonzert = value.fkKonzert;
        this.instrument = value.instrument;
        this.token = value.token;
        this.expiresAt = value.expiresAt;
        this.active = value.active;
        this.createdAt = value.createdAt;
    }

    public NotenShareLink(
        Long id,
        Long fkKonzert,
        String instrument,
        UUID token,
        LocalDateTime expiresAt,
        Boolean active,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.fkKonzert = fkKonzert;
        this.instrument = instrument;
        this.token = token;
        this.expiresAt = expiresAt;
        this.active = active;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.noten_share_link.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.noten_share_link.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.noten_share_link.fk_konzert</code>.
     */
    public Long getFkKonzert() {
        return this.fkKonzert;
    }

    /**
     * Setter for <code>public.noten_share_link.fk_konzert</code>.
     */
    public void setFkKonzert(Long fkKonzert) {
        this.fkKonzert = fkKonzert;
    }

    /**
     * Getter for <code>public.noten_share_link.instrument</code>.
     */
    public String getInstrument() {
        return this.instrument;
    }

    /**
     * Setter for <code>public.noten_share_link.instrument</code>.
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument;
    }

    /**
     * Getter for <code>public.noten_share_link.token</code>.
     */
    public UUID getToken() {
        return this.token;
    }

    /**
     * Setter for <code>public.noten_share_link.token</code>.
     */
    public void setToken(UUID token) {
        this.token = token;
    }

    /**
     * Getter for <code>public.noten_share_link.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for <code>public.noten_share_link.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for <code>public.noten_share_link.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.noten_share_link.active</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * Getter for <code>public.noten_share_link.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.noten_share_link.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final NotenShareLink other = (NotenShareLink) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fkKonzert == null) {
            if (other.fkKonzert != null)
                return false;
        }
        else if (!this.fkKonzert.equals(other.fkKonzert))
            return false;
        if (this.instrument == null) {
            if (other.instrument != null)
                return false;
        }
        else if (!this.instrument.equals(other.instrument))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fkKonzert == null) ? 0 : this.fkKonzert.hashCode());
        result = prime * result + ((this.instrument == null) ? 0 : this.instrument.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotenShareLink (");

        sb.append(id);
        sb.append(", ").append(fkKonzert);
        sb.append(", ").append(instrument);
        sb.append(", ").append(token);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(active);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
