/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PassivmitgliedPayment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long fkPassivmitglied;
    private LocalDate datum;
    private BigDecimal amount;
    private String bemerkung;
    private LocalDateTime createdAt;
    private String createdBy;

    public PassivmitgliedPayment() {}

    public PassivmitgliedPayment(PassivmitgliedPayment value) {
        this.id = value.id;
        this.fkPassivmitglied = value.fkPassivmitglied;
        this.datum = value.datum;
        this.amount = value.amount;
        this.bemerkung = value.bemerkung;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
    }

    public PassivmitgliedPayment(
        Long id,
        Long fkPassivmitglied,
        LocalDate datum,
        BigDecimal amount,
        String bemerkung,
        LocalDateTime createdAt,
        String createdBy
    ) {
        this.id = id;
        this.fkPassivmitglied = fkPassivmitglied;
        this.datum = datum;
        this.amount = amount;
        this.bemerkung = bemerkung;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.fk_passivmitglied</code>.
     */
    public Long getFkPassivmitglied() {
        return this.fkPassivmitglied;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.fk_passivmitglied</code>.
     */
    public void setFkPassivmitglied(Long fkPassivmitglied) {
        this.fkPassivmitglied = fkPassivmitglied;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.datum</code>.
     */
    public LocalDate getDatum() {
        return this.datum;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.datum</code>.
     */
    public void setDatum(LocalDate datum) {
        this.datum = datum;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.bemerkung</code>.
     */
    public String getBemerkung() {
        return this.bemerkung;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.bemerkung</code>.
     */
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.passivmitglied_payment.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.passivmitglied_payment.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PassivmitgliedPayment other = (PassivmitgliedPayment) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fkPassivmitglied == null) {
            if (other.fkPassivmitglied != null)
                return false;
        }
        else if (!this.fkPassivmitglied.equals(other.fkPassivmitglied))
            return false;
        if (this.datum == null) {
            if (other.datum != null)
                return false;
        }
        else if (!this.datum.equals(other.datum))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.bemerkung == null) {
            if (other.bemerkung != null)
                return false;
        }
        else if (!this.bemerkung.equals(other.bemerkung))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fkPassivmitglied == null) ? 0 : this.fkPassivmitglied.hashCode());
        result = prime * result + ((this.datum == null) ? 0 : this.datum.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.bemerkung == null) ? 0 : this.bemerkung.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PassivmitgliedPayment (");

        sb.append(id);
        sb.append(", ").append(fkPassivmitglied);
        sb.append(", ").append(datum);
        sb.append(", ").append(amount);
        sb.append(", ").append(bemerkung);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);

        sb.append(")");
        return sb.toString();
    }
}
