/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PassivmitgliedVoucher implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long fkPassivmitglied;
    private String code;
    private String description;
    private LocalDate validUntil;
    private LocalDateTime redeemedAt;
    private String redeemedBy;

    public PassivmitgliedVoucher() {}

    public PassivmitgliedVoucher(PassivmitgliedVoucher value) {
        this.id = value.id;
        this.fkPassivmitglied = value.fkPassivmitglied;
        this.code = value.code;
        this.description = value.description;
        this.validUntil = value.validUntil;
        this.redeemedAt = value.redeemedAt;
        this.redeemedBy = value.redeemedBy;
    }

    public PassivmitgliedVoucher(
        Long id,
        Long fkPassivmitglied,
        String code,
        String description,
        LocalDate validUntil,
        LocalDateTime redeemedAt,
        String redeemedBy
    ) {
        this.id = id;
        this.fkPassivmitglied = fkPassivmitglied;
        this.code = code;
        this.description = description;
        this.validUntil = validUntil;
        this.redeemedAt = redeemedAt;
        this.redeemedBy = redeemedBy;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.fk_passivmitglied</code>.
     */
    public Long getFkPassivmitglied() {
        return this.fkPassivmitglied;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.fk_passivmitglied</code>.
     */
    public void setFkPassivmitglied(Long fkPassivmitglied) {
        this.fkPassivmitglied = fkPassivmitglied;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.valid_until</code>.
     */
    public LocalDate getValidUntil() {
        return this.validUntil;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.valid_until</code>.
     */
    public void setValidUntil(LocalDate validUntil) {
        this.validUntil = validUntil;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.redeemed_at</code>.
     */
    public LocalDateTime getRedeemedAt() {
        return this.redeemedAt;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.redeemed_at</code>.
     */
    public void setRedeemedAt(LocalDateTime redeemedAt) {
        this.redeemedAt = redeemedAt;
    }

    /**
     * Getter for <code>public.passivmitglied_voucher.redeemed_by</code>.
     */
    public String getRedeemedBy() {
        return this.redeemedBy;
    }

    /**
     * Setter for <code>public.passivmitglied_voucher.redeemed_by</code>.
     */
    public void setRedeemedBy(String redeemedBy) {
        this.redeemedBy = redeemedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PassivmitgliedVoucher other = (PassivmitgliedVoucher) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fkPassivmitglied == null) {
            if (other.fkPassivmitglied != null)
                return false;
        }
        else if (!this.fkPassivmitglied.equals(other.fkPassivmitglied))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.validUntil == null) {
            if (other.validUntil != null)
                return false;
        }
        else if (!this.validUntil.equals(other.validUntil))
            return false;
        if (this.redeemedAt == null) {
            if (other.redeemedAt != null)
                return false;
        }
        else if (!this.redeemedAt.equals(other.redeemedAt))
            return false;
        if (this.redeemedBy == null) {
            if (other.redeemedBy != null)
                return false;
        }
        else if (!this.redeemedBy.equals(other.redeemedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fkPassivmitglied == null) ? 0 : this.fkPassivmitglied.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.validUntil == null) ? 0 : this.validUntil.hashCode());
        result = prime * result + ((this.redeemedAt == null) ? 0 : this.redeemedAt.hashCode());
        result = prime * result + ((this.redeemedBy == null) ? 0 : this.redeemedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PassivmitgliedVoucher (");

        sb.append(id);
        sb.append(", ").append(fkPassivmitglied);
        sb.append(", ").append(code);
        sb.append(", ").append(description);
        sb.append(", ").append(validUntil);
        sb.append(", ").append(redeemedAt);
        sb.append(", ").append(redeemedBy);

        sb.append(")");
        return sb.toString();
    }
}
