/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserCredentials implements Serializable {

    private static final long serialVersionUID = 1L;

    private String credentialId;
    private String userEntityUserId;
    private byte[] publicKey;
    private Long signatureCount;
    private Boolean uvInitialized;
    private Boolean backupEligible;
    private String authenticatorTransports;
    private String publicKeyCredentialType;
    private Boolean backupState;
    private byte[] attestationObject;
    private byte[] attestationClientDataJson;
    private LocalDateTime created;
    private LocalDateTime lastUsed;
    private String label;

    public UserCredentials() {}

    public UserCredentials(UserCredentials value) {
        this.credentialId = value.credentialId;
        this.userEntityUserId = value.userEntityUserId;
        this.publicKey = value.publicKey;
        this.signatureCount = value.signatureCount;
        this.uvInitialized = value.uvInitialized;
        this.backupEligible = value.backupEligible;
        this.authenticatorTransports = value.authenticatorTransports;
        this.publicKeyCredentialType = value.publicKeyCredentialType;
        this.backupState = value.backupState;
        this.attestationObject = value.attestationObject;
        this.attestationClientDataJson = value.attestationClientDataJson;
        this.created = value.created;
        this.lastUsed = value.lastUsed;
        this.label = value.label;
    }

    public UserCredentials(
        String credentialId,
        String userEntityUserId,
        byte[] publicKey,
        Long signatureCount,
        Boolean uvInitialized,
        Boolean backupEligible,
        String authenticatorTransports,
        String publicKeyCredentialType,
        Boolean backupState,
        byte[] attestationObject,
        byte[] attestationClientDataJson,
        LocalDateTime created,
        LocalDateTime lastUsed,
        String label
    ) {
        this.credentialId = credentialId;
        this.userEntityUserId = userEntityUserId;
        this.publicKey = publicKey;
        this.signatureCount = signatureCount;
        this.uvInitialized = uvInitialized;
        this.backupEligible = backupEligible;
        this.authenticatorTransports = authenticatorTransports;
        this.publicKeyCredentialType = publicKeyCredentialType;
        this.backupState = backupState;
        this.attestationObject = attestationObject;
        this.attestationClientDataJson = attestationClientDataJson;
        this.created = created;
        this.lastUsed = lastUsed;
        this.label = label;
    }

    /**
     * Getter for <code>public.user_credentials.credential_id</code>.
     */
    public String getCredentialId() {
        return this.credentialId;
    }

    /**
     * Setter for <code>public.user_credentials.credential_id</code>.
     */
    public void setCredentialId(String credentialId) {
        this.credentialId = credentialId;
    }

    /**
     * Getter for <code>public.user_credentials.user_entity_user_id</code>.
     */
    public String getUserEntityUserId() {
        return this.userEntityUserId;
    }

    /**
     * Setter for <code>public.user_credentials.user_entity_user_id</code>.
     */
    public void setUserEntityUserId(String userEntityUserId) {
        this.userEntityUserId = userEntityUserId;
    }

    /**
     * Getter for <code>public.user_credentials.public_key</code>.
     */
    public byte[] getPublicKey() {
        return this.publicKey;
    }

    /**
     * Setter for <code>public.user_credentials.public_key</code>.
     */
    public void setPublicKey(byte[] publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * Getter for <code>public.user_credentials.signature_count</code>.
     */
    public Long getSignatureCount() {
        return this.signatureCount;
    }

    /**
     * Setter for <code>public.user_credentials.signature_count</code>.
     */
    public void setSignatureCount(Long signatureCount) {
        this.signatureCount = signatureCount;
    }

    /**
     * Getter for <code>public.user_credentials.uv_initialized</code>.
     */
    public Boolean getUvInitialized() {
        return this.uvInitialized;
    }

    /**
     * Setter for <code>public.user_credentials.uv_initialized</code>.
     */
    public void setUvInitialized(Boolean uvInitialized) {
        this.uvInitialized = uvInitialized;
    }

    /**
     * Getter for <code>public.user_credentials.backup_eligible</code>.
     */
    public Boolean getBackupEligible() {
        return this.backupEligible;
    }

    /**
     * Setter for <code>public.user_credentials.backup_eligible</code>.
     */
    public void setBackupEligible(Boolean backupEligible) {
        this.backupEligible = backupEligible;
    }

    /**
     * Getter for <code>public.user_credentials.authenticator_transports</code>.
     */
    public String getAuthenticatorTransports() {
        return this.authenticatorTransports;
    }

    /**
     * Setter for <code>public.user_credentials.authenticator_transports</code>.
     */
    public void setAuthenticatorTransports(String authenticatorTransports) {
        this.authenticatorTransports = authenticatorTransports;
    }

    /**
     * Getter for
     * <code>public.user_credentials.public_key_credential_type</code>.
     */
    public String getPublicKeyCredentialType() {
        return this.publicKeyCredentialType;
    }

    /**
     * Setter for
     * <code>public.user_credentials.public_key_credential_type</code>.
     */
    public void setPublicKeyCredentialType(String publicKeyCredentialType) {
        this.publicKeyCredentialType = publicKeyCredentialType;
    }

    /**
     * Getter for <code>public.user_credentials.backup_state</code>.
     */
    public Boolean getBackupState() {
        return this.backupState;
    }

    /**
     * Setter for <code>public.user_credentials.backup_state</code>.
     */
    public void setBackupState(Boolean backupState) {
        this.backupState = backupState;
    }

    /**
     * Getter for <code>public.user_credentials.attestation_object</code>.
     */
    public byte[] getAttestationObject() {
        return this.attestationObject;
    }

    /**
     * Setter for <code>public.user_credentials.attestation_object</code>.
     */
    public void setAttestationObject(byte[] attestationObject) {
        this.attestationObject = attestationObject;
    }

    /**
     * Getter for
     * <code>public.user_credentials.attestation_client_data_json</code>.
     */
    public byte[] getAttestationClientDataJson() {
        return this.attestationClientDataJson;
    }

    /**
     * Setter for
     * <code>public.user_credentials.attestation_client_data_json</code>.
     */
    public void setAttestationClientDataJson(byte[] attestationClientDataJson) {
        this.attestationClientDataJson = attestationClientDataJson;
    }

    /**
     * Getter for <code>public.user_credentials.created</code>.
     */
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>public.user_credentials.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for <code>public.user_credentials.last_used</code>.
     */
    public LocalDateTime getLastUsed() {
        return this.lastUsed;
    }

    /**
     * Setter for <code>public.user_credentials.last_used</code>.
     */
    public void setLastUsed(LocalDateTime lastUsed) {
        this.lastUsed = lastUsed;
    }

    /**
     * Getter for <code>public.user_credentials.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>public.user_credentials.label</code>.
     */
    public void setLabel(String label) {
        this.label = label;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserCredentials other = (UserCredentials) obj;
        if (this.credentialId == null) {
            if (other.credentialId != null)
                return false;
        }
        else if (!this.credentialId.equals(other.credentialId))
            return false;
        if (this.userEntityUserId == null) {
            if (other.userEntityUserId != null)
                return false;
        }
        else if (!this.userEntityUserId.equals(other.userEntityUserId))
            return false;
        if (this.publicKey == null) {
            if (other.publicKey != null)
                return false;
        }
        else if (!Arrays.equals(this.publicKey, other.publicKey))
            return false;
        if (this.signatureCount == null) {
            if (other.signatureCount != null)
                return false;
        }
        else if (!this.signatureCount.equals(other.signatureCount))
            return false;
        if (this.uvInitialized == null) {
            if (other.uvInitialized != null)
                return false;
        }
        else if (!this.uvInitialized.equals(other.uvInitialized))
            return false;
        if (this.backupEligible == null) {
            if (other.backupEligible != null)
                return false;
        }
        else if (!this.backupEligible.equals(other.backupEligible))
            return false;
        if (this.authenticatorTransports == null) {
            if (other.authenticatorTransports != null)
                return false;
        }
        else if (!this.authenticatorTransports.equals(other.authenticatorTransports))
            return false;
        if (this.publicKeyCredentialType == null) {
            if (other.publicKeyCredentialType != null)
                return false;
        }
        else if (!this.publicKeyCredentialType.equals(other.publicKeyCredentialType))
            return false;
        if (this.backupState == null) {
            if (other.backupState != null)
                return false;
        }
        else if (!this.backupState.equals(other.backupState))
            return false;
        if (this.attestationObject == null) {
            if (other.attestationObject != null)
                return false;
        }
        else if (!Arrays.equals(this.attestationObject, other.attestationObject))
            return false;
        if (this.attestationClientDataJson == null) {
            if (other.attestationClientDataJson != null)
                return false;
        }
        else if (!Arrays.equals(this.attestationClientDataJson, other.attestationClientDataJson))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.lastUsed == null) {
            if (other.lastUsed != null)
                return false;
        }
        else if (!this.lastUsed.equals(other.lastUsed))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.credentialId == null) ? 0 : this.credentialId.hashCode());
        result = prime * result + ((this.userEntityUserId == null) ? 0 : this.userEntityUserId.hashCode());
        result = prime * result + ((this.publicKey == null) ? 0 : Arrays.hashCode(this.publicKey));
        result = prime * result + ((this.signatureCount == null) ? 0 : this.signatureCount.hashCode());
        result = prime * result + ((this.uvInitialized == null) ? 0 : this.uvInitialized.hashCode());
        result = prime * result + ((this.backupEligible == null) ? 0 : this.backupEligible.hashCode());
        result = prime * result + ((this.authenticatorTransports == null) ? 0 : this.authenticatorTransports.hashCode());
        result = prime * result + ((this.publicKeyCredentialType == null) ? 0 : this.publicKeyCredentialType.hashCode());
        result = prime * result + ((this.backupState == null) ? 0 : this.backupState.hashCode());
        result = prime * result + ((this.attestationObject == null) ? 0 : Arrays.hashCode(this.attestationObject));
        result = prime * result + ((this.attestationClientDataJson == null) ? 0 : Arrays.hashCode(this.attestationClientDataJson));
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.lastUsed == null) ? 0 : this.lastUsed.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserCredentials (");

        sb.append(credentialId);
        sb.append(", ").append(userEntityUserId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(signatureCount);
        sb.append(", ").append(uvInitialized);
        sb.append(", ").append(backupEligible);
        sb.append(", ").append(authenticatorTransports);
        sb.append(", ").append(publicKeyCredentialType);
        sb.append(", ").append(backupState);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(created);
        sb.append(", ").append(lastUsed);
        sb.append(", ").append(label);

        sb.append(")");
        return sb.toString();
    }
}
