POST https://admin.mvurdorf.ch/api/passivmitglied
Content-Type: application/json

{
  "vorname": "Hans",
  "nachname": "Muster",
  "strasse": "Bahnhofsstrasse 1",
  "ort": "8000 Zürich",
  "email": "hans.muster1@test.com",
  "bemerkung": "Hallo!",
  "kommunikationPost": false,
  "kommunikationEmail": true,
  "payments": []
}

###
