POST {{base}}/supporter
Content-Type: application/json

{
  "type": "PASSIVMITGLIED",
  "anrede": "Lieber",
  "vorname": "Hans",
  "nachname": "Muster",
  "strasse": "Bahnhofsstrasse",
  "strasseNr": "1",
  "plz": "8000",
  "ort": "8000 Zürich",
  "countryCode": "CH",
  "email": "hans.muster1@test.com",
  "bemerkung": "Hallo!",
  "kommunikationPost": false,
  "kommunikationEmail": true,
  "payments": [],
  "vouchers": []
}

###

GET {{base}}/supporter/1000001

###
