/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.NotenShareLink;
import ch.mvurdorf.platform.jooq.tables.records.NotenShareLinkRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class NotenShareLinkDao extends AbstractSpringDAOImpl<NotenShareLinkRecord, ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink, Long> {

    /**
     * Create a new NotenShareLinkDao without any configuration
     */
    public NotenShareLinkDao() {
        super(NotenShareLink.NOTEN_SHARE_LINK, ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink.class);
    }

    /**
     * Create a new NotenShareLinkDao with an attached configuration
     */
    @Autowired
    public NotenShareLinkDao(Configuration configuration) {
        super(NotenShareLink.NOTEN_SHARE_LINK, ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink.class, configuration);
    }

    @Override
    public Long getId(ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchById(Long... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink fetchOneById(Long value) {
        return fetchOne(NotenShareLink.NOTEN_SHARE_LINK.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchOptionalById(Long value) {
        return fetchOptional(NotenShareLink.NOTEN_SHARE_LINK.ID, value);
    }

    /**
     * Fetch records that have <code>fk_konzert BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfFkKonzert(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.FK_KONZERT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fk_konzert IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchByFkKonzert(Long... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.FK_KONZERT, values);
    }

    /**
     * Fetch records that have <code>instrument BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfInstrument(String lowerInclusive, String upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.INSTRUMENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>instrument IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchByInstrument(String... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.INSTRUMENT, values);
    }

    /**
     * Fetch records that have <code>token BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfToken(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchByToken(UUID... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink fetchOneByToken(UUID value) {
        return fetchOne(NotenShareLink.NOTEN_SHARE_LINK.TOKEN, value);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchOptionalByToken(UUID value) {
        return fetchOptional(NotenShareLink.NOTEN_SHARE_LINK.TOKEN, value);
    }

    /**
     * Fetch records that have <code>expires_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expires_at IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchByExpiresAt(LocalDateTime... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchByActive(Boolean... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotenShareLink.NOTEN_SHARE_LINK.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.NotenShareLink> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(NotenShareLink.NOTEN_SHARE_LINK.CREATED_AT, values);
    }
}
