/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.Passivmitglied;
import ch.mvurdorf.platform.jooq.tables.records.PassivmitgliedRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class PassivmitgliedDao extends AbstractSpringDAOImpl<PassivmitgliedRecord, ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied, Long> {

    /**
     * Create a new PassivmitgliedDao without any configuration
     */
    public PassivmitgliedDao() {
        super(Passivmitglied.PASSIVMITGLIED, ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied.class);
    }

    /**
     * Create a new PassivmitgliedDao with an attached configuration
     */
    @Autowired
    public PassivmitgliedDao(Configuration configuration) {
        super(Passivmitglied.PASSIVMITGLIED, ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied.class, configuration);
    }

    @Override
    public Long getId(ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchById(Long... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied fetchOneById(Long value) {
        return fetchOne(Passivmitglied.PASSIVMITGLIED.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchOptionalById(Long value) {
        return fetchOptional(Passivmitglied.PASSIVMITGLIED.ID, value);
    }

    /**
     * Fetch records that have <code>vorname BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfVorname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.VORNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>vorname IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByVorname(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.VORNAME, values);
    }

    /**
     * Fetch records that have <code>nachname BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfNachname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.NACHNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>nachname IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByNachname(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.NACHNAME, values);
    }

    /**
     * Fetch records that have <code>strasse BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfStrasse(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.STRASSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>strasse IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByStrasse(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.STRASSE, values);
    }

    /**
     * Fetch records that have <code>ort BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfOrt(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.ORT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ort IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByOrt(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.ORT, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByEmail(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied fetchOneByEmail(String value) {
        return fetchOne(Passivmitglied.PASSIVMITGLIED.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchOptionalByEmail(String value) {
        return fetchOptional(Passivmitglied.PASSIVMITGLIED.EMAIL, value);
    }

    /**
     * Fetch records that have <code>bemerkung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfBemerkung(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.BEMERKUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bemerkung IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByBemerkung(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.BEMERKUNG, values);
    }

    /**
     * Fetch records that have <code>kommunikation_post BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfKommunikationPost(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.KOMMUNIKATION_POST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>kommunikation_post IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByKommunikationPost(Boolean... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.KOMMUNIKATION_POST, values);
    }

    /**
     * Fetch records that have <code>kommunikation_email BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfKommunikationEmail(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.KOMMUNIKATION_EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>kommunikation_email IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByKommunikationEmail(Boolean... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.KOMMUNIKATION_EMAIL, values);
    }

    /**
     * Fetch records that have <code>registered_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfRegisteredAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.REGISTERED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>registered_at IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByRegisteredAt(LocalDateTime... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.REGISTERED_AT, values);
    }

    /**
     * Fetch records that have <code>external_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfExternalId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.EXTERNAL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>external_id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByExternalId(Long... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.EXTERNAL_ID, values);
    }

    /**
     * Fetch records that have <code>anrede BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfAnrede(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.ANREDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>anrede IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByAnrede(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.ANREDE, values);
    }

    /**
     * Fetch records that have <code>uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfUuid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByUuid(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.UUID, values);
    }

    /**
     * Fetch records that have <code>plz BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfPlz(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.PLZ, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>plz IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByPlz(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.PLZ, values);
    }

    /**
     * Fetch records that have <code>strasse_nr BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfStrasseNr(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.STRASSE_NR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>strasse_nr IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByStrasseNr(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.STRASSE_NR, values);
    }

    /**
     * Fetch records that have <code>country_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchRangeOfCountryCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Passivmitglied.PASSIVMITGLIED.COUNTRY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>country_code IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.Passivmitglied> fetchByCountryCode(String... values) {
        return fetch(Passivmitglied.PASSIVMITGLIED.COUNTRY_CODE, values);
    }
}
