/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.PassivmitgliedPayment;
import ch.mvurdorf.platform.jooq.tables.records.PassivmitgliedPaymentRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class PassivmitgliedPaymentDao extends AbstractSpringDAOImpl<PassivmitgliedPaymentRecord, ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment, Long> {

    /**
     * Create a new PassivmitgliedPaymentDao without any configuration
     */
    public PassivmitgliedPaymentDao() {
        super(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT, ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment.class);
    }

    /**
     * Create a new PassivmitgliedPaymentDao with an attached configuration
     */
    @Autowired
    public PassivmitgliedPaymentDao(Configuration configuration) {
        super(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT, ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment.class, configuration);
    }

    @Override
    public Long getId(ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchById(Long... values) {
        return fetch(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment fetchOneById(Long value) {
        return fetchOne(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchOptionalById(Long value) {
        return fetchOptional(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.ID, value);
    }

    /**
     * Fetch records that have <code>fk_passivmitglied BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchRangeOfFkPassivmitglied(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.FK_PASSIVMITGLIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fk_passivmitglied IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchByFkPassivmitglied(Long... values) {
        return fetch(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.FK_PASSIVMITGLIED, values);
    }

    /**
     * Fetch records that have <code>datum BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchRangeOfDatum(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.DATUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datum IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchByDatum(LocalDate... values) {
        return fetch(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.DATUM, values);
    }

    /**
     * Fetch records that have <code>amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchRangeOfAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchByAmount(BigDecimal... values) {
        return fetch(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>bemerkung BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchRangeOfBemerkung(String lowerInclusive, String upperInclusive) {
        return fetchRange(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.BEMERKUNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bemerkung IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.PassivmitgliedPayment> fetchByBemerkung(String... values) {
        return fetch(PassivmitgliedPayment.PASSIVMITGLIED_PAYMENT.BEMERKUNG, values);
    }
}
