/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.ShareableLink;
import ch.mvurdorf.platform.jooq.tables.records.ShareableLinkRecord;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ShareableLinkDao extends AbstractSpringDAOImpl<ShareableLinkRecord, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink, Long> {

    /**
     * Create a new ShareableLinkDao without any configuration
     */
    public ShareableLinkDao() {
        super(ShareableLink.SHAREABLE_LINK, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink.class);
    }

    /**
     * Create a new ShareableLinkDao with an attached configuration
     */
    @Autowired
    public ShareableLinkDao(Configuration configuration) {
        super(ShareableLink.SHAREABLE_LINK, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink.class, configuration);
    }

    @Override
    public Long getId(ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ShareableLink.SHAREABLE_LINK.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchById(Long... values) {
        return fetch(ShareableLink.SHAREABLE_LINK.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink fetchOneById(Long value) {
        return fetchOne(ShareableLink.SHAREABLE_LINK.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchOptionalById(Long value) {
        return fetchOptional(ShareableLink.SHAREABLE_LINK.ID, value);
    }

    /**
     * Fetch records that have <code>uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchRangeOfUuid(String lowerInclusive, String upperInclusive) {
        return fetchRange(ShareableLink.SHAREABLE_LINK.UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchByUuid(String... values) {
        return fetch(ShareableLink.SHAREABLE_LINK.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink fetchOneByUuid(String value) {
        return fetchOne(ShareableLink.SHAREABLE_LINK.UUID, value);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchOptionalByUuid(String value) {
        return fetchOptional(ShareableLink.SHAREABLE_LINK.UUID, value);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(ShareableLink.SHAREABLE_LINK.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchByDescription(String... values) {
        return fetch(ShareableLink.SHAREABLE_LINK.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>valid_until BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchRangeOfValidUntil(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ShareableLink.SHAREABLE_LINK.VALID_UNTIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valid_until IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLink> fetchByValidUntil(LocalDate... values) {
        return fetch(ShareableLink.SHAREABLE_LINK.VALID_UNTIL, values);
    }
}
