/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.ShareableLinkInstrument;
import ch.mvurdorf.platform.jooq.tables.records.ShareableLinkInstrumentRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ShareableLinkInstrumentDao extends AbstractSpringDAOImpl<ShareableLinkInstrumentRecord, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument, Long> {

    /**
     * Create a new ShareableLinkInstrumentDao without any configuration
     */
    public ShareableLinkInstrumentDao() {
        super(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument.class);
    }

    /**
     * Create a new ShareableLinkInstrumentDao with an attached configuration
     */
    @Autowired
    public ShareableLinkInstrumentDao(Configuration configuration) {
        super(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument.class, configuration);
    }

    @Override
    public Long getId(ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchById(Long... values) {
        return fetch(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument fetchOneById(Long value) {
        return fetchOne(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchOptionalById(Long value) {
        return fetchOptional(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.ID, value);
    }

    /**
     * Fetch records that have <code>shareable_link_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchRangeOfShareableLinkId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.SHAREABLE_LINK_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>shareable_link_id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchByShareableLinkId(Long... values) {
        return fetch(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.SHAREABLE_LINK_ID, values);
    }

    /**
     * Fetch records that have <code>instrument BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchRangeOfInstrument(String lowerInclusive, String upperInclusive) {
        return fetchRange(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.INSTRUMENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>instrument IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkInstrument> fetchByInstrument(String... values) {
        return fetch(ShareableLinkInstrument.SHAREABLE_LINK_INSTRUMENT.INSTRUMENT, values);
    }
}
