/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.ShareableLinkKomposition;
import ch.mvurdorf.platform.jooq.tables.records.ShareableLinkKompositionRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ShareableLinkKompositionDao extends AbstractSpringDAOImpl<ShareableLinkKompositionRecord, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition, Long> {

    /**
     * Create a new ShareableLinkKompositionDao without any configuration
     */
    public ShareableLinkKompositionDao() {
        super(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition.class);
    }

    /**
     * Create a new ShareableLinkKompositionDao with an attached configuration
     */
    @Autowired
    public ShareableLinkKompositionDao(Configuration configuration) {
        super(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION, ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition.class, configuration);
    }

    @Override
    public Long getId(ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchById(Long... values) {
        return fetch(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition fetchOneById(Long value) {
        return fetchOne(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchOptionalById(Long value) {
        return fetchOptional(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.ID, value);
    }

    /**
     * Fetch records that have <code>shareable_link_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchRangeOfShareableLinkId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.SHAREABLE_LINK_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>shareable_link_id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchByShareableLinkId(Long... values) {
        return fetch(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.SHAREABLE_LINK_ID, values);
    }

    /**
     * Fetch records that have <code>komposition_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchRangeOfKompositionId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.KOMPOSITION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>komposition_id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.ShareableLinkKomposition> fetchByKompositionId(Long... values) {
        return fetch(ShareableLinkKomposition.SHAREABLE_LINK_KOMPOSITION.KOMPOSITION_ID, values);
    }
}
