/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables.daos;


import ch.mvurdorf.platform.jooq.AbstractSpringDAOImpl;
import ch.mvurdorf.platform.jooq.tables.UserCredentials;
import ch.mvurdorf.platform.jooq.tables.records.UserCredentialsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class UserCredentialsDao extends AbstractSpringDAOImpl<UserCredentialsRecord, ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials, String> {

    /**
     * Create a new UserCredentialsDao without any configuration
     */
    public UserCredentialsDao() {
        super(UserCredentials.USER_CREDENTIALS, ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials.class);
    }

    /**
     * Create a new UserCredentialsDao with an attached configuration
     */
    @Autowired
    public UserCredentialsDao(Configuration configuration) {
        super(UserCredentials.USER_CREDENTIALS, ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials.class, configuration);
    }

    @Override
    public String getId(ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials object) {
        return object.getCredentialId();
    }

    /**
     * Fetch records that have <code>credential_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfCredentialId(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.CREDENTIAL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>credential_id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByCredentialId(String... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.CREDENTIAL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>credential_id = value</code>
     */
    public ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials fetchOneByCredentialId(String value) {
        return fetchOne(UserCredentials.USER_CREDENTIALS.CREDENTIAL_ID, value);
    }

    /**
     * Fetch a unique record that has <code>credential_id = value</code>
     */
    public Optional<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchOptionalByCredentialId(String value) {
        return fetchOptional(UserCredentials.USER_CREDENTIALS.CREDENTIAL_ID, value);
    }

    /**
     * Fetch records that have <code>user_entity_user_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfUserEntityUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.USER_ENTITY_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_entity_user_id IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByUserEntityUserId(String... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.USER_ENTITY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>public_key BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfPublicKey(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.PUBLIC_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>public_key IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByPublicKey(byte[]... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.PUBLIC_KEY, values);
    }

    /**
     * Fetch records that have <code>signature_count BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfSignatureCount(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.SIGNATURE_COUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>signature_count IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchBySignatureCount(Long... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.SIGNATURE_COUNT, values);
    }

    /**
     * Fetch records that have <code>uv_initialized BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfUvInitialized(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.UV_INITIALIZED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uv_initialized IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByUvInitialized(Boolean... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.UV_INITIALIZED, values);
    }

    /**
     * Fetch records that have <code>backup_eligible BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfBackupEligible(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.BACKUP_ELIGIBLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>backup_eligible IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByBackupEligible(Boolean... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.BACKUP_ELIGIBLE, values);
    }

    /**
     * Fetch records that have <code>authenticator_transports BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfAuthenticatorTransports(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.AUTHENTICATOR_TRANSPORTS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authenticator_transports IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByAuthenticatorTransports(String... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.AUTHENTICATOR_TRANSPORTS, values);
    }

    /**
     * Fetch records that have <code>public_key_credential_type BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfPublicKeyCredentialType(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.PUBLIC_KEY_CREDENTIAL_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>public_key_credential_type IN
     * (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByPublicKeyCredentialType(String... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.PUBLIC_KEY_CREDENTIAL_TYPE, values);
    }

    /**
     * Fetch records that have <code>backup_state BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfBackupState(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.BACKUP_STATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>backup_state IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByBackupState(Boolean... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.BACKUP_STATE, values);
    }

    /**
     * Fetch records that have <code>attestation_object BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfAttestationObject(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.ATTESTATION_OBJECT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attestation_object IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByAttestationObject(byte[]... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.ATTESTATION_OBJECT, values);
    }

    /**
     * Fetch records that have <code>attestation_client_data_json BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfAttestationClientDataJson(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.ATTESTATION_CLIENT_DATA_JSON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attestation_client_data_json IN
     * (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByAttestationClientDataJson(byte[]... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.ATTESTATION_CLIENT_DATA_JSON, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByCreated(LocalDateTime... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.CREATED, values);
    }

    /**
     * Fetch records that have <code>last_used BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfLastUsed(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.LAST_USED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_used IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByLastUsed(LocalDateTime... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.LAST_USED, values);
    }

    /**
     * Fetch records that have <code>label BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchRangeOfLabel(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserCredentials.USER_CREDENTIALS.LABEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<ch.mvurdorf.platform.jooq.tables.pojos.UserCredentials> fetchByLabel(String... values) {
        return fetch(UserCredentials.USER_CREDENTIALS.LABEL, values);
    }
}
