/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.passivmitglied_id_seq</code>
     */
    public static final Sequence<Long> PASSIVMITGLIED_ID_SEQ = Internal.createSequence("passivmitglied_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.passivmitglied_payment_id_seq</code>
     */
    public static final Sequence<Long> PASSIVMITGLIED_PAYMENT_ID_SEQ = Internal.createSequence("passivmitglied_payment_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.passivmitglied_voucher_id_seq</code>
     */
    public static final Sequence<Long> PASSIVMITGLIED_VOUCHER_ID_SEQ = Internal.createSequence("passivmitglied_voucher_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
