/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq;


import ch.mvurdorf.platform.jooq.tables.Komposition;
import ch.mvurdorf.platform.jooq.tables.Konzert;
import ch.mvurdorf.platform.jooq.tables.KonzertEntry;
import ch.mvurdorf.platform.jooq.tables.Login;
import ch.mvurdorf.platform.jooq.tables.Noten;
import ch.mvurdorf.platform.jooq.tables.Repertoire;
import ch.mvurdorf.platform.jooq.tables.RepertoireEntry;
import ch.mvurdorf.platform.jooq.tables.Supporter;
import ch.mvurdorf.platform.jooq.tables.SupporterPayment;
import ch.mvurdorf.platform.jooq.tables.SupporterVoucher;
import ch.mvurdorf.platform.jooq.tables.Voucher;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.komposition</code>.
     */
    public static final Komposition KOMPOSITION = Komposition.KOMPOSITION;

    /**
     * The table <code>public.konzert</code>.
     */
    public static final Konzert KONZERT = Konzert.KONZERT;

    /**
     * The table <code>public.konzert_entry</code>.
     */
    public static final KonzertEntry KONZERT_ENTRY = KonzertEntry.KONZERT_ENTRY;

    /**
     * The table <code>public.login</code>.
     */
    public static final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>public.noten</code>.
     */
    public static final Noten NOTEN = Noten.NOTEN;

    /**
     * The table <code>public.repertoire</code>.
     */
    public static final Repertoire REPERTOIRE = Repertoire.REPERTOIRE;

    /**
     * The table <code>public.repertoire_entry</code>.
     */
    public static final RepertoireEntry REPERTOIRE_ENTRY = RepertoireEntry.REPERTOIRE_ENTRY;

    /**
     * The table <code>public.supporter</code>.
     */
    public static final Supporter SUPPORTER = Supporter.SUPPORTER;

    /**
     * The table <code>public.supporter_payment</code>.
     */
    public static final SupporterPayment SUPPORTER_PAYMENT = SupporterPayment.SUPPORTER_PAYMENT;

    /**
     * The table <code>public.supporter_voucher</code>.
     */
    public static final SupporterVoucher SUPPORTER_VOUCHER = SupporterVoucher.SUPPORTER_VOUCHER;

    /**
     * The table <code>public.voucher</code>.
     */
    public static final Voucher VOUCHER = Voucher.VOUCHER;
}
