/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq;


import ch.mvurdorf.platform.jooq.tables.Komposition;
import ch.mvurdorf.platform.jooq.tables.Login;
import ch.mvurdorf.platform.jooq.tables.Noten;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.komposition</code>.
     */
    public static final Komposition KOMPOSITION = Komposition.KOMPOSITION;

    /**
     * The table <code>public.login</code>.
     */
    public static final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>public.noten</code>.
     */
    public static final Noten NOTEN = Noten.NOTEN;
}
