/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.records.InstrumentPermissionRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InstrumentPermission extends TableImpl<InstrumentPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.instrument_permission</code>
     */
    public static final InstrumentPermission INSTRUMENT_PERMISSION = new InstrumentPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstrumentPermissionRecord> getRecordType() {
        return InstrumentPermissionRecord.class;
    }

    /**
     * The column <code>public.instrument_permission.fk_login</code>.
     */
    public final TableField<InstrumentPermissionRecord, Long> FK_LOGIN = createField(DSL.name("fk_login"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.instrument_permission.instrument</code>.
     */
    public final TableField<InstrumentPermissionRecord, String> INSTRUMENT = createField(DSL.name("instrument"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private InstrumentPermission(Name alias, Table<InstrumentPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InstrumentPermission(Name alias, Table<InstrumentPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.instrument_permission</code> table
     * reference
     */
    public InstrumentPermission(String alias) {
        this(DSL.name(alias), INSTRUMENT_PERMISSION);
    }

    /**
     * Create an aliased <code>public.instrument_permission</code> table
     * reference
     */
    public InstrumentPermission(Name alias) {
        this(alias, INSTRUMENT_PERMISSION);
    }

    /**
     * Create a <code>public.instrument_permission</code> table reference
     */
    public InstrumentPermission() {
        this(DSL.name("instrument_permission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<InstrumentPermissionRecord> getPrimaryKey() {
        return Keys.PK__INSTRUMENTS_PERMISSION;
    }

    @Override
    public InstrumentPermission as(String alias) {
        return new InstrumentPermission(DSL.name(alias), this);
    }

    @Override
    public InstrumentPermission as(Name alias) {
        return new InstrumentPermission(alias, this);
    }

    @Override
    public InstrumentPermission as(Table<?> alias) {
        return new InstrumentPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InstrumentPermission rename(String name) {
        return new InstrumentPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstrumentPermission rename(Name name) {
        return new InstrumentPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstrumentPermission rename(Table<?> name) {
        return new InstrumentPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstrumentPermission where(Condition condition) {
        return new InstrumentPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstrumentPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstrumentPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstrumentPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstrumentPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstrumentPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstrumentPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstrumentPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstrumentPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstrumentPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
