/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Indexes;
import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.Konzert.KonzertPath;
import ch.mvurdorf.platform.jooq.tables.records.NotenShareLinkRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotenShareLink extends TableImpl<NotenShareLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.noten_share_link</code>
     */
    public static final NotenShareLink NOTEN_SHARE_LINK = new NotenShareLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotenShareLinkRecord> getRecordType() {
        return NotenShareLinkRecord.class;
    }

    /**
     * The column <code>public.noten_share_link.id</code>.
     */
    public final TableField<NotenShareLinkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.noten_share_link.fk_konzert</code>.
     */
    public final TableField<NotenShareLinkRecord, Long> FK_KONZERT = createField(DSL.name("fk_konzert"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.noten_share_link.instrument</code>.
     */
    public final TableField<NotenShareLinkRecord, String> INSTRUMENT = createField(DSL.name("instrument"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.noten_share_link.token</code>.
     */
    public final TableField<NotenShareLinkRecord, UUID> TOKEN = createField(DSL.name("token"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.noten_share_link.expires_at</code>.
     */
    public final TableField<NotenShareLinkRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.noten_share_link.active</code>.
     */
    public final TableField<NotenShareLinkRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.noten_share_link.created_at</code>.
     */
    public final TableField<NotenShareLinkRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private NotenShareLink(Name alias, Table<NotenShareLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NotenShareLink(Name alias, Table<NotenShareLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.noten_share_link</code> table reference
     */
    public NotenShareLink(String alias) {
        this(DSL.name(alias), NOTEN_SHARE_LINK);
    }

    /**
     * Create an aliased <code>public.noten_share_link</code> table reference
     */
    public NotenShareLink(Name alias) {
        this(alias, NOTEN_SHARE_LINK);
    }

    /**
     * Create a <code>public.noten_share_link</code> table reference
     */
    public NotenShareLink() {
        this(DSL.name("noten_share_link"), null);
    }

    public <O extends Record> NotenShareLink(Table<O> path, ForeignKey<O, NotenShareLinkRecord> childPath, InverseForeignKey<O, NotenShareLinkRecord> parentPath) {
        super(path, childPath, parentPath, NOTEN_SHARE_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class NotenShareLinkPath extends NotenShareLink implements Path<NotenShareLinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> NotenShareLinkPath(Table<O> path, ForeignKey<O, NotenShareLinkRecord> childPath, InverseForeignKey<O, NotenShareLinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private NotenShareLinkPath(Name alias, Table<NotenShareLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public NotenShareLinkPath as(String alias) {
            return new NotenShareLinkPath(DSL.name(alias), this);
        }

        @Override
        public NotenShareLinkPath as(Name alias) {
            return new NotenShareLinkPath(alias, this);
        }

        @Override
        public NotenShareLinkPath as(Table<?> alias) {
            return new NotenShareLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTEN_SHARE_LINK_KONZERT_INSTRUMENT);
    }

    @Override
    public Identity<NotenShareLinkRecord, Long> getIdentity() {
        return (Identity<NotenShareLinkRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<NotenShareLinkRecord> getPrimaryKey() {
        return Keys.NOTEN_SHARE_LINK_PKEY;
    }

    @Override
    public List<UniqueKey<NotenShareLinkRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NOTEN_SHARE_LINK_TOKEN_KEY);
    }

    @Override
    public List<ForeignKey<NotenShareLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NOTEN_SHARE_LINK__NOTEN_SHARE_LINK_FK_KONZERT_FKEY);
    }

    private transient KonzertPath _konzert;

    /**
     * Get the implicit join path to the <code>public.konzert</code> table.
     */
    public KonzertPath konzert() {
        if (_konzert == null)
            _konzert = new KonzertPath(this, Keys.NOTEN_SHARE_LINK__NOTEN_SHARE_LINK_FK_KONZERT_FKEY, null);

        return _konzert;
    }

    @Override
    public NotenShareLink as(String alias) {
        return new NotenShareLink(DSL.name(alias), this);
    }

    @Override
    public NotenShareLink as(Name alias) {
        return new NotenShareLink(alias, this);
    }

    @Override
    public NotenShareLink as(Table<?> alias) {
        return new NotenShareLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotenShareLink rename(String name) {
        return new NotenShareLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotenShareLink rename(Name name) {
        return new NotenShareLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotenShareLink rename(Table<?> name) {
        return new NotenShareLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotenShareLink where(Condition condition) {
        return new NotenShareLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotenShareLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotenShareLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotenShareLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotenShareLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotenShareLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotenShareLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotenShareLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotenShareLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotenShareLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
