/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.Passivmitglied.PassivmitgliedPath;
import ch.mvurdorf.platform.jooq.tables.records.PassivmitgliedPaymentRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PassivmitgliedPayment extends TableImpl<PassivmitgliedPaymentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.passivmitglied_payment</code>
     */
    public static final PassivmitgliedPayment PASSIVMITGLIED_PAYMENT = new PassivmitgliedPayment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PassivmitgliedPaymentRecord> getRecordType() {
        return PassivmitgliedPaymentRecord.class;
    }

    /**
     * The column <code>public.passivmitglied_payment.id</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.passivmitglied_payment.fk_passivmitglied</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, Long> FK_PASSIVMITGLIED = createField(DSL.name("fk_passivmitglied"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied_payment.datum</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, LocalDate> DATUM = createField(DSL.name("datum"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied_payment.amount</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(6, 2).nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied_payment.bemerkung</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, String> BEMERKUNG = createField(DSL.name("bemerkung"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.passivmitglied_payment.created_at</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.passivmitglied_payment.created_by</code>.
     */
    public final TableField<PassivmitgliedPaymentRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.field(DSL.raw("'System'::character varying"), SQLDataType.VARCHAR)), this, "");

    private PassivmitgliedPayment(Name alias, Table<PassivmitgliedPaymentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PassivmitgliedPayment(Name alias, Table<PassivmitgliedPaymentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.passivmitglied_payment</code> table
     * reference
     */
    public PassivmitgliedPayment(String alias) {
        this(DSL.name(alias), PASSIVMITGLIED_PAYMENT);
    }

    /**
     * Create an aliased <code>public.passivmitglied_payment</code> table
     * reference
     */
    public PassivmitgliedPayment(Name alias) {
        this(alias, PASSIVMITGLIED_PAYMENT);
    }

    /**
     * Create a <code>public.passivmitglied_payment</code> table reference
     */
    public PassivmitgliedPayment() {
        this(DSL.name("passivmitglied_payment"), null);
    }

    public <O extends Record> PassivmitgliedPayment(Table<O> path, ForeignKey<O, PassivmitgliedPaymentRecord> childPath, InverseForeignKey<O, PassivmitgliedPaymentRecord> parentPath) {
        super(path, childPath, parentPath, PASSIVMITGLIED_PAYMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PassivmitgliedPaymentPath extends PassivmitgliedPayment implements Path<PassivmitgliedPaymentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PassivmitgliedPaymentPath(Table<O> path, ForeignKey<O, PassivmitgliedPaymentRecord> childPath, InverseForeignKey<O, PassivmitgliedPaymentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PassivmitgliedPaymentPath(Name alias, Table<PassivmitgliedPaymentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PassivmitgliedPaymentPath as(String alias) {
            return new PassivmitgliedPaymentPath(DSL.name(alias), this);
        }

        @Override
        public PassivmitgliedPaymentPath as(Name alias) {
            return new PassivmitgliedPaymentPath(alias, this);
        }

        @Override
        public PassivmitgliedPaymentPath as(Table<?> alias) {
            return new PassivmitgliedPaymentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PassivmitgliedPaymentRecord, Long> getIdentity() {
        return (Identity<PassivmitgliedPaymentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PassivmitgliedPaymentRecord> getPrimaryKey() {
        return Keys.PK__PASSIVMITGLIED_PAYMENT;
    }

    @Override
    public List<ForeignKey<PassivmitgliedPaymentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PASSIVMITGLIED_PAYMENT__PASSIVMITGLIED_PAYMENT_FK_PASSIVMITGLIED_FKEY);
    }

    private transient PassivmitgliedPath _passivmitglied;

    /**
     * Get the implicit join path to the <code>public.passivmitglied</code>
     * table.
     */
    public PassivmitgliedPath passivmitglied() {
        if (_passivmitglied == null)
            _passivmitglied = new PassivmitgliedPath(this, Keys.PASSIVMITGLIED_PAYMENT__PASSIVMITGLIED_PAYMENT_FK_PASSIVMITGLIED_FKEY, null);

        return _passivmitglied;
    }

    @Override
    public PassivmitgliedPayment as(String alias) {
        return new PassivmitgliedPayment(DSL.name(alias), this);
    }

    @Override
    public PassivmitgliedPayment as(Name alias) {
        return new PassivmitgliedPayment(alias, this);
    }

    @Override
    public PassivmitgliedPayment as(Table<?> alias) {
        return new PassivmitgliedPayment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PassivmitgliedPayment rename(String name) {
        return new PassivmitgliedPayment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PassivmitgliedPayment rename(Name name) {
        return new PassivmitgliedPayment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PassivmitgliedPayment rename(Table<?> name) {
        return new PassivmitgliedPayment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PassivmitgliedPayment where(Condition condition) {
        return new PassivmitgliedPayment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PassivmitgliedPayment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PassivmitgliedPayment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PassivmitgliedPayment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PassivmitgliedPayment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PassivmitgliedPayment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PassivmitgliedPayment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PassivmitgliedPayment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PassivmitgliedPayment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PassivmitgliedPayment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
