/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.PassivmitgliedPayment.PassivmitgliedPaymentPath;
import ch.mvurdorf.platform.jooq.tables.records.PassivmitgliedRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Passivmitglied extends TableImpl<PassivmitgliedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.passivmitglied</code>
     */
    public static final Passivmitglied PASSIVMITGLIED = new Passivmitglied();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PassivmitgliedRecord> getRecordType() {
        return PassivmitgliedRecord.class;
    }

    /**
     * The column <code>public.passivmitglied.id</code>.
     */
    public final TableField<PassivmitgliedRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.passivmitglied.vorname</code>.
     */
    public final TableField<PassivmitgliedRecord, String> VORNAME = createField(DSL.name("vorname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.nachname</code>.
     */
    public final TableField<PassivmitgliedRecord, String> NACHNAME = createField(DSL.name("nachname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.strasse</code>.
     */
    public final TableField<PassivmitgliedRecord, String> STRASSE = createField(DSL.name("strasse"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.ort</code>.
     */
    public final TableField<PassivmitgliedRecord, String> ORT = createField(DSL.name("ort"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.email</code>.
     */
    public final TableField<PassivmitgliedRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.bemerkung</code>.
     */
    public final TableField<PassivmitgliedRecord, String> BEMERKUNG = createField(DSL.name("bemerkung"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.passivmitglied.kommunikation_post</code>.
     */
    public final TableField<PassivmitgliedRecord, Boolean> KOMMUNIKATION_POST = createField(DSL.name("kommunikation_post"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.kommunikation_email</code>.
     */
    public final TableField<PassivmitgliedRecord, Boolean> KOMMUNIKATION_EMAIL = createField(DSL.name("kommunikation_email"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.passivmitglied.registered_at</code>.
     */
    public final TableField<PassivmitgliedRecord, LocalDateTime> REGISTERED_AT = createField(DSL.name("registered_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.passivmitglied.external_id</code>.
     */
    public final TableField<PassivmitgliedRecord, Long> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "");

    private Passivmitglied(Name alias, Table<PassivmitgliedRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Passivmitglied(Name alias, Table<PassivmitgliedRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.passivmitglied</code> table reference
     */
    public Passivmitglied(String alias) {
        this(DSL.name(alias), PASSIVMITGLIED);
    }

    /**
     * Create an aliased <code>public.passivmitglied</code> table reference
     */
    public Passivmitglied(Name alias) {
        this(alias, PASSIVMITGLIED);
    }

    /**
     * Create a <code>public.passivmitglied</code> table reference
     */
    public Passivmitglied() {
        this(DSL.name("passivmitglied"), null);
    }

    public <O extends Record> Passivmitglied(Table<O> path, ForeignKey<O, PassivmitgliedRecord> childPath, InverseForeignKey<O, PassivmitgliedRecord> parentPath) {
        super(path, childPath, parentPath, PASSIVMITGLIED);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PassivmitgliedPath extends Passivmitglied implements Path<PassivmitgliedRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PassivmitgliedPath(Table<O> path, ForeignKey<O, PassivmitgliedRecord> childPath, InverseForeignKey<O, PassivmitgliedRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PassivmitgliedPath(Name alias, Table<PassivmitgliedRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PassivmitgliedPath as(String alias) {
            return new PassivmitgliedPath(DSL.name(alias), this);
        }

        @Override
        public PassivmitgliedPath as(Name alias) {
            return new PassivmitgliedPath(alias, this);
        }

        @Override
        public PassivmitgliedPath as(Table<?> alias) {
            return new PassivmitgliedPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PassivmitgliedRecord, Long> getIdentity() {
        return (Identity<PassivmitgliedRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PassivmitgliedRecord> getPrimaryKey() {
        return Keys.PK__PASSIVMITGLIED;
    }

    @Override
    public List<UniqueKey<PassivmitgliedRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PASSIVMITGLIED_EMAIL_KEY);
    }

    private transient PassivmitgliedPaymentPath _passivmitgliedPayment;

    /**
     * Get the implicit to-many join path to the
     * <code>public.passivmitglied_payment</code> table
     */
    public PassivmitgliedPaymentPath passivmitgliedPayment() {
        if (_passivmitgliedPayment == null)
            _passivmitgliedPayment = new PassivmitgliedPaymentPath(this, null, Keys.PASSIVMITGLIED_PAYMENT__PASSIVMITGLIED_PAYMENT_FK_PASSIVMITGLIED_FKEY.getInverseKey());

        return _passivmitgliedPayment;
    }

    @Override
    public Passivmitglied as(String alias) {
        return new Passivmitglied(DSL.name(alias), this);
    }

    @Override
    public Passivmitglied as(Name alias) {
        return new Passivmitglied(alias, this);
    }

    @Override
    public Passivmitglied as(Table<?> alias) {
        return new Passivmitglied(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Passivmitglied rename(String name) {
        return new Passivmitglied(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Passivmitglied rename(Name name) {
        return new Passivmitglied(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Passivmitglied rename(Table<?> name) {
        return new Passivmitglied(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Passivmitglied where(Condition condition) {
        return new Passivmitglied(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Passivmitglied where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Passivmitglied where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Passivmitglied where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Passivmitglied where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Passivmitglied where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Passivmitglied where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Passivmitglied where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Passivmitglied whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Passivmitglied whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
