/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.ShareableLinkInstrument.ShareableLinkInstrumentPath;
import ch.mvurdorf.platform.jooq.tables.ShareableLinkKomposition.ShareableLinkKompositionPath;
import ch.mvurdorf.platform.jooq.tables.records.ShareableLinkRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShareableLink extends TableImpl<ShareableLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shareable_link</code>
     */
    public static final ShareableLink SHAREABLE_LINK = new ShareableLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShareableLinkRecord> getRecordType() {
        return ShareableLinkRecord.class;
    }

    /**
     * The column <code>public.shareable_link.id</code>.
     */
    public final TableField<ShareableLinkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.shareable_link.uuid</code>.
     */
    public final TableField<ShareableLinkRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.shareable_link.description</code>.
     */
    public final TableField<ShareableLinkRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.shareable_link.valid_until</code>.
     */
    public final TableField<ShareableLinkRecord, LocalDate> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private ShareableLink(Name alias, Table<ShareableLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShareableLink(Name alias, Table<ShareableLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shareable_link</code> table reference
     */
    public ShareableLink(String alias) {
        this(DSL.name(alias), SHAREABLE_LINK);
    }

    /**
     * Create an aliased <code>public.shareable_link</code> table reference
     */
    public ShareableLink(Name alias) {
        this(alias, SHAREABLE_LINK);
    }

    /**
     * Create a <code>public.shareable_link</code> table reference
     */
    public ShareableLink() {
        this(DSL.name("shareable_link"), null);
    }

    public <O extends Record> ShareableLink(Table<O> path, ForeignKey<O, ShareableLinkRecord> childPath, InverseForeignKey<O, ShareableLinkRecord> parentPath) {
        super(path, childPath, parentPath, SHAREABLE_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShareableLinkPath extends ShareableLink implements Path<ShareableLinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShareableLinkPath(Table<O> path, ForeignKey<O, ShareableLinkRecord> childPath, InverseForeignKey<O, ShareableLinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShareableLinkPath(Name alias, Table<ShareableLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShareableLinkPath as(String alias) {
            return new ShareableLinkPath(DSL.name(alias), this);
        }

        @Override
        public ShareableLinkPath as(Name alias) {
            return new ShareableLinkPath(alias, this);
        }

        @Override
        public ShareableLinkPath as(Table<?> alias) {
            return new ShareableLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ShareableLinkRecord, Long> getIdentity() {
        return (Identity<ShareableLinkRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShareableLinkRecord> getPrimaryKey() {
        return Keys.PK__SHAREABLE_LINK;
    }

    @Override
    public List<UniqueKey<ShareableLinkRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ__SHAREABLE_LINK);
    }

    private transient ShareableLinkInstrumentPath _shareableLinkInstrument;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shareable_link_instrument</code> table
     */
    public ShareableLinkInstrumentPath shareableLinkInstrument() {
        if (_shareableLinkInstrument == null)
            _shareableLinkInstrument = new ShareableLinkInstrumentPath(this, null, Keys.SHAREABLE_LINK_INSTRUMENT__FK__SHAREABLE_LINK_INSTRUMENT_LINK.getInverseKey());

        return _shareableLinkInstrument;
    }

    private transient ShareableLinkKompositionPath _shareableLinkKomposition;

    /**
     * Get the implicit to-many join path to the
     * <code>public.shareable_link_komposition</code> table
     */
    public ShareableLinkKompositionPath shareableLinkKomposition() {
        if (_shareableLinkKomposition == null)
            _shareableLinkKomposition = new ShareableLinkKompositionPath(this, null, Keys.SHAREABLE_LINK_KOMPOSITION__FK__SHAREABLE_LINK_KOMPOSITION_LINK.getInverseKey());

        return _shareableLinkKomposition;
    }

    @Override
    public ShareableLink as(String alias) {
        return new ShareableLink(DSL.name(alias), this);
    }

    @Override
    public ShareableLink as(Name alias) {
        return new ShareableLink(alias, this);
    }

    @Override
    public ShareableLink as(Table<?> alias) {
        return new ShareableLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShareableLink rename(String name) {
        return new ShareableLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShareableLink rename(Name name) {
        return new ShareableLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShareableLink rename(Table<?> name) {
        return new ShareableLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLink where(Condition condition) {
        return new ShareableLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
