/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.Komposition.KompositionPath;
import ch.mvurdorf.platform.jooq.tables.ShareableLink.ShareableLinkPath;
import ch.mvurdorf.platform.jooq.tables.records.ShareableLinkKompositionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShareableLinkKomposition extends TableImpl<ShareableLinkKompositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shareable_link_komposition</code>
     */
    public static final ShareableLinkKomposition SHAREABLE_LINK_KOMPOSITION = new ShareableLinkKomposition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShareableLinkKompositionRecord> getRecordType() {
        return ShareableLinkKompositionRecord.class;
    }

    /**
     * The column <code>public.shareable_link_komposition.id</code>.
     */
    public final TableField<ShareableLinkKompositionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.shareable_link_komposition.shareable_link_id</code>.
     */
    public final TableField<ShareableLinkKompositionRecord, Long> SHAREABLE_LINK_ID = createField(DSL.name("shareable_link_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.shareable_link_komposition.komposition_id</code>.
     */
    public final TableField<ShareableLinkKompositionRecord, Long> KOMPOSITION_ID = createField(DSL.name("komposition_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private ShareableLinkKomposition(Name alias, Table<ShareableLinkKompositionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShareableLinkKomposition(Name alias, Table<ShareableLinkKompositionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shareable_link_komposition</code> table
     * reference
     */
    public ShareableLinkKomposition(String alias) {
        this(DSL.name(alias), SHAREABLE_LINK_KOMPOSITION);
    }

    /**
     * Create an aliased <code>public.shareable_link_komposition</code> table
     * reference
     */
    public ShareableLinkKomposition(Name alias) {
        this(alias, SHAREABLE_LINK_KOMPOSITION);
    }

    /**
     * Create a <code>public.shareable_link_komposition</code> table reference
     */
    public ShareableLinkKomposition() {
        this(DSL.name("shareable_link_komposition"), null);
    }

    public <O extends Record> ShareableLinkKomposition(Table<O> path, ForeignKey<O, ShareableLinkKompositionRecord> childPath, InverseForeignKey<O, ShareableLinkKompositionRecord> parentPath) {
        super(path, childPath, parentPath, SHAREABLE_LINK_KOMPOSITION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShareableLinkKompositionPath extends ShareableLinkKomposition implements Path<ShareableLinkKompositionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShareableLinkKompositionPath(Table<O> path, ForeignKey<O, ShareableLinkKompositionRecord> childPath, InverseForeignKey<O, ShareableLinkKompositionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShareableLinkKompositionPath(Name alias, Table<ShareableLinkKompositionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShareableLinkKompositionPath as(String alias) {
            return new ShareableLinkKompositionPath(DSL.name(alias), this);
        }

        @Override
        public ShareableLinkKompositionPath as(Name alias) {
            return new ShareableLinkKompositionPath(alias, this);
        }

        @Override
        public ShareableLinkKompositionPath as(Table<?> alias) {
            return new ShareableLinkKompositionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ShareableLinkKompositionRecord, Long> getIdentity() {
        return (Identity<ShareableLinkKompositionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShareableLinkKompositionRecord> getPrimaryKey() {
        return Keys.PK__SHAREABLE_LINK_NOTEN;
    }

    @Override
    public List<ForeignKey<ShareableLinkKompositionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHAREABLE_LINK_KOMPOSITION__FK__SHAREABLE_LINK_KOMPOSITION_KOMP, Keys.SHAREABLE_LINK_KOMPOSITION__FK__SHAREABLE_LINK_KOMPOSITION_LINK);
    }

    private transient KompositionPath _komposition;

    /**
     * Get the implicit join path to the <code>public.komposition</code> table.
     */
    public KompositionPath komposition() {
        if (_komposition == null)
            _komposition = new KompositionPath(this, Keys.SHAREABLE_LINK_KOMPOSITION__FK__SHAREABLE_LINK_KOMPOSITION_KOMP, null);

        return _komposition;
    }

    private transient ShareableLinkPath _shareableLink;

    /**
     * Get the implicit join path to the <code>public.shareable_link</code>
     * table.
     */
    public ShareableLinkPath shareableLink() {
        if (_shareableLink == null)
            _shareableLink = new ShareableLinkPath(this, Keys.SHAREABLE_LINK_KOMPOSITION__FK__SHAREABLE_LINK_KOMPOSITION_LINK, null);

        return _shareableLink;
    }

    @Override
    public ShareableLinkKomposition as(String alias) {
        return new ShareableLinkKomposition(DSL.name(alias), this);
    }

    @Override
    public ShareableLinkKomposition as(Name alias) {
        return new ShareableLinkKomposition(alias, this);
    }

    @Override
    public ShareableLinkKomposition as(Table<?> alias) {
        return new ShareableLinkKomposition(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShareableLinkKomposition rename(String name) {
        return new ShareableLinkKomposition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShareableLinkKomposition rename(Name name) {
        return new ShareableLinkKomposition(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShareableLinkKomposition rename(Table<?> name) {
        return new ShareableLinkKomposition(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLinkKomposition where(Condition condition) {
        return new ShareableLinkKomposition(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLinkKomposition where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLinkKomposition where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLinkKomposition where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLinkKomposition where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLinkKomposition where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLinkKomposition where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShareableLinkKomposition where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLinkKomposition whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShareableLinkKomposition whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
