/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Indexes;
import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.UserEntities.UserEntitiesPath;
import ch.mvurdorf.platform.jooq.tables.records.UserCredentialsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserCredentials extends TableImpl<UserCredentialsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_credentials</code>
     */
    public static final UserCredentials USER_CREDENTIALS = new UserCredentials();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserCredentialsRecord> getRecordType() {
        return UserCredentialsRecord.class;
    }

    /**
     * The column <code>public.user_credentials.credential_id</code>.
     */
    public final TableField<UserCredentialsRecord, String> CREDENTIAL_ID = createField(DSL.name("credential_id"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.user_credentials.user_entity_user_id</code>.
     */
    public final TableField<UserCredentialsRecord, String> USER_ENTITY_USER_ID = createField(DSL.name("user_entity_user_id"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.user_credentials.public_key</code>.
     */
    public final TableField<UserCredentialsRecord, byte[]> PUBLIC_KEY = createField(DSL.name("public_key"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.user_credentials.signature_count</code>.
     */
    public final TableField<UserCredentialsRecord, Long> SIGNATURE_COUNT = createField(DSL.name("signature_count"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user_credentials.uv_initialized</code>.
     */
    public final TableField<UserCredentialsRecord, Boolean> UV_INITIALIZED = createField(DSL.name("uv_initialized"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.user_credentials.backup_eligible</code>.
     */
    public final TableField<UserCredentialsRecord, Boolean> BACKUP_ELIGIBLE = createField(DSL.name("backup_eligible"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_credentials.authenticator_transports</code>.
     */
    public final TableField<UserCredentialsRecord, String> AUTHENTICATOR_TRANSPORTS = createField(DSL.name("authenticator_transports"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column
     * <code>public.user_credentials.public_key_credential_type</code>.
     */
    public final TableField<UserCredentialsRecord, String> PUBLIC_KEY_CREDENTIAL_TYPE = createField(DSL.name("public_key_credential_type"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.user_credentials.backup_state</code>.
     */
    public final TableField<UserCredentialsRecord, Boolean> BACKUP_STATE = createField(DSL.name("backup_state"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.user_credentials.attestation_object</code>.
     */
    public final TableField<UserCredentialsRecord, byte[]> ATTESTATION_OBJECT = createField(DSL.name("attestation_object"), SQLDataType.BLOB, this, "");

    /**
     * The column
     * <code>public.user_credentials.attestation_client_data_json</code>.
     */
    public final TableField<UserCredentialsRecord, byte[]> ATTESTATION_CLIENT_DATA_JSON = createField(DSL.name("attestation_client_data_json"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.user_credentials.created</code>.
     */
    public final TableField<UserCredentialsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.user_credentials.last_used</code>.
     */
    public final TableField<UserCredentialsRecord, LocalDateTime> LAST_USED = createField(DSL.name("last_used"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.user_credentials.label</code>.
     */
    public final TableField<UserCredentialsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    private UserCredentials(Name alias, Table<UserCredentialsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserCredentials(Name alias, Table<UserCredentialsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_credentials</code> table reference
     */
    public UserCredentials(String alias) {
        this(DSL.name(alias), USER_CREDENTIALS);
    }

    /**
     * Create an aliased <code>public.user_credentials</code> table reference
     */
    public UserCredentials(Name alias) {
        this(alias, USER_CREDENTIALS);
    }

    /**
     * Create a <code>public.user_credentials</code> table reference
     */
    public UserCredentials() {
        this(DSL.name("user_credentials"), null);
    }

    public <O extends Record> UserCredentials(Table<O> path, ForeignKey<O, UserCredentialsRecord> childPath, InverseForeignKey<O, UserCredentialsRecord> parentPath) {
        super(path, childPath, parentPath, USER_CREDENTIALS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserCredentialsPath extends UserCredentials implements Path<UserCredentialsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserCredentialsPath(Table<O> path, ForeignKey<O, UserCredentialsRecord> childPath, InverseForeignKey<O, UserCredentialsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserCredentialsPath(Name alias, Table<UserCredentialsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserCredentialsPath as(String alias) {
            return new UserCredentialsPath(DSL.name(alias), this);
        }

        @Override
        public UserCredentialsPath as(Name alias) {
            return new UserCredentialsPath(alias, this);
        }

        @Override
        public UserCredentialsPath as(Table<?> alias) {
            return new UserCredentialsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX__USER_CREDENTIALS__USER_ENTITY_USER_ID);
    }

    @Override
    public UniqueKey<UserCredentialsRecord> getPrimaryKey() {
        return Keys.PK__USER_CREDENTIALS;
    }

    @Override
    public List<ForeignKey<UserCredentialsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_CREDENTIALS__FK__USER_CREDENTIALS__USER_ENTITIES);
    }

    private transient UserEntitiesPath _userEntities;

    /**
     * Get the implicit join path to the <code>public.user_entities</code>
     * table.
     */
    public UserEntitiesPath userEntities() {
        if (_userEntities == null)
            _userEntities = new UserEntitiesPath(this, Keys.USER_CREDENTIALS__FK__USER_CREDENTIALS__USER_ENTITIES, null);

        return _userEntities;
    }

    @Override
    public UserCredentials as(String alias) {
        return new UserCredentials(DSL.name(alias), this);
    }

    @Override
    public UserCredentials as(Name alias) {
        return new UserCredentials(alias, this);
    }

    @Override
    public UserCredentials as(Table<?> alias) {
        return new UserCredentials(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCredentials rename(String name) {
        return new UserCredentials(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCredentials rename(Name name) {
        return new UserCredentials(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCredentials rename(Table<?> name) {
        return new UserCredentials(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserCredentials where(Condition condition) {
        return new UserCredentials(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserCredentials where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserCredentials where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserCredentials where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserCredentials where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserCredentials where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserCredentials where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserCredentials where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserCredentials whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserCredentials whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
