/*
 * This file is generated by jOOQ.
 */
package ch.mvurdorf.platform.jooq.tables;


import ch.mvurdorf.platform.jooq.Keys;
import ch.mvurdorf.platform.jooq.Public;
import ch.mvurdorf.platform.jooq.tables.records.VoucherRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Voucher extends TableImpl<VoucherRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.voucher</code>
     */
    public static final Voucher VOUCHER = new Voucher();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VoucherRecord> getRecordType() {
        return VoucherRecord.class;
    }

    /**
     * The column <code>public.voucher.id</code>.
     */
    public final TableField<VoucherRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.voucher.code_prefix</code>.
     */
    public final TableField<VoucherRecord, String> CODE_PREFIX = createField(DSL.name("code_prefix"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.voucher.description</code>.
     */
    public final TableField<VoucherRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.voucher.valid_until</code>.
     */
    public final TableField<VoucherRecord, LocalDate> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private Voucher(Name alias, Table<VoucherRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Voucher(Name alias, Table<VoucherRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.voucher</code> table reference
     */
    public Voucher(String alias) {
        this(DSL.name(alias), VOUCHER);
    }

    /**
     * Create an aliased <code>public.voucher</code> table reference
     */
    public Voucher(Name alias) {
        this(alias, VOUCHER);
    }

    /**
     * Create a <code>public.voucher</code> table reference
     */
    public Voucher() {
        this(DSL.name("voucher"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<VoucherRecord, Long> getIdentity() {
        return (Identity<VoucherRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VoucherRecord> getPrimaryKey() {
        return Keys.PK__VOUCHER;
    }

    @Override
    public Voucher as(String alias) {
        return new Voucher(DSL.name(alias), this);
    }

    @Override
    public Voucher as(Name alias) {
        return new Voucher(alias, this);
    }

    @Override
    public Voucher as(Table<?> alias) {
        return new Voucher(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Voucher rename(String name) {
        return new Voucher(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Voucher rename(Name name) {
        return new Voucher(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Voucher rename(Table<?> name) {
        return new Voucher(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Voucher where(Condition condition) {
        return new Voucher(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Voucher where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Voucher where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Voucher where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Voucher where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Voucher where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Voucher where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Voucher where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Voucher whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Voucher whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
